In [1]:
# numpy and pandas for data manipulation
import numpy as np
import pandas as pd 

# sklearn preprocessing for dealing with categorical variables
from sklearn.preprocessing import LabelEncoder

# File system manangement
import os


# matplotlib and seaborn for plotting
import matplotlib.pyplot as plt
import seaborn as sns 

windows_dir = "../kaggle/all/"
ubuntu_dir = "/home/prof/kaggle/unbankedcredit/kaggle/all/"

import platform

system = platform.system()

print("Notebook is running on operating system: {}".format(system))
if system == "Linux":
    directory = ubuntu_dir
else:
    directory = windows_dir

Notebook is running on operating system: Linux

In [2]:
train_file = "/home/prof/kaggle/unbankedcredit/train_enhanced_loan_history_cc_pos_previous.csv"
train_pd = pd.read_csv(train_file, low_memory=True)
train_pd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307511 entries, 0 to 307510
Columns: 961 entries, SK_ID_CURR to PREVIOUS_COUNT
dtypes: bool(1), float64(786), int64(173), object(1)
memory usage: 2.2+ GB

In [3]:
# Test data
test_file = "/home/prof/kaggle/unbankedcredit/test_enhanced_loan_history_cc_pos_previous.csv"
# collist.remove('TARGET')
# test_pd = pd.read_csv(test_file, usecols=collist)
test_pd = pd.read_csv(test_file)
print('Training data shape: ', test_pd.shape)
test_pd.info()

Training data shape:  (48744, 960)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48744 entries, 0 to 48743
Columns: 960 entries, SK_ID_CURR to PREVIOUS_COUNT
dtypes: bool(1), float64(786), int64(172), object(1)
memory usage: 356.7+ MB

Downcasting to reduce memory overhead

In [4]:
train_pd = train_pd.apply(pd.to_numeric,errors="coerce", downcast="integer")

In [5]:
train_pd = train_pd.apply(pd.to_numeric,errors="coerce", downcast="float")

In [6]:
test_pd = test_pd.apply(pd.to_numeric,errors="coerce", downcast="integer")

In [7]:
test_pd = test_pd.apply(pd.to_numeric,errors="coerce", downcast="float")

In [17]:
pd.options.display.max_rows = 100
# Find correlations with the target and sort
correlations = train_pd.corr()['TARGET'].sort_values(ascending=False)

TARGET                                  1.000000
AMT_BALANCE_CREDIT_RATIO_MEANS          0.135560
CNT_DRAWINGS_ATM_CURRENT_MEANS          0.107692
AMT_DRAWINGS_CURRENT_RATIO_MEANS        0.098962
AMT_DRAWINGS_ATM_CURRENT_RATIO_MEANS    0.090357
Name: TARGET, dtype: float64

In [26]:
# # Display correlations
# print('Most Positive Correlations:\n', correlations.tail(100))
# correlations
pos_list = [x[0] for x in correlations.tail(100).items()]
print(pos_list)

['NAME_YIELD_GROUP_low_action_SUM', 'LIVINGAPARTMENTS_AVG', 'NAME_FAMILY_STATUS_Married', 'AMT_DOWN_PAYMENT_MAX', 'NAME_SELLER_INDUSTRY_Furniture_SUM', 'PRODUCT_COMBINATION_POS industry with interest', 'PRODUCT_COMBINATION_POS household without interest_MAX', 'NAME_CLIENT_TYPE_Refreshed_MEAN', 'AMT_DOWN_PAYMENT_SUM', 'APARTMENTS_MODE', 'NUM_INSTALMENT_VERSION_MEANS', 'NAME_YIELD_GROUP_low_normal_SUM', 'NAME_HOUSING_TYPE_House / apartment', 'FLAG_DOCUMENT_6', 'NAME_SELLER_INDUSTRY_Furniture_MEAN', 'CNT_INSTALMENT_MATURE_CUM_MEANS', 'NAME_GOODS_CATEGORY_Furniture_SUM', 'AMT_ANNUITY_MAX', 'APARTMENTS_MEDI', 'NAME_SELLER_INDUSTRY_Furniture_MAX', 'NAME_YIELD_GROUP_low_action_MEAN', 'APARTMENTS_AVG', 'NUM_INSTALMENT_VERSION_SUMS', 'NAME_GOODS_CATEGORY_Furniture_MEAN', 'NAME_YIELD_GROUP_low_normal', 'AMT_ANNUITY_y', 'DAYS_IN_ADVANCE_SUMS', 'AMT_CREDIT_x', 'RATE_DOWN_PAYMENT', 'LIVINGAREA_MODE', 'PRODUCT_COMBINATION_POS industry with interest_SUM', 'HOUR_APPR_PROCESS_START_MAX', 'NAME_CONTRACT_TYPE', 'NAME_GOODS_CATEGORY_Furniture_MAX', 'NAME_CONTRACT_STATUS_1_SUM', 'ELEVATORS_MODE', 'TOTALAREA_MODE', 'NAME_CONTRACT_TYPE_Consumer loans_MEAN', 'NAME_CLIENT_TYPE_Refreshed_MAX', 'FLOORSMIN_MODE', 'NAME_YIELD_GROUP_low_action_MAX', 'LIVINGAREA_MEDI', 'LIVINGAREA_AVG', 'WALLSMATERIAL_MODE_Panel', 'FLOORSMIN_MEDI', 'RATE_DOWN_PAYMENT_MEAN', 'FLOORSMIN_AVG', 'NAME_CONTRACT_TYPE_Consumer loans', 'ELEVATORS_MEDI', 'PRODUCT_COMBINATION_POS industry with interest_MEAN', 'HOUR_APPR_PROCESS_START_y', 'ELEVATORS_AVG', 'NAME_PORTFOLIO_POS_MEAN', 'PRODUCT_COMBINATION_POS industry with interest_MAX', 'NAME_PAYMENT_TYPE_Cash through the bank_MEAN', 'AMT_ANNUITY_MEAN', 'POS_COUNT', 'HOUR_APPR_PROCESS_START_MEAN', 'NAME_PORTFOLIO_POS', 'PRODUCT_COMBINATION_Cash X-Sell: low_MAX', 'NAME_PAYMENT_TYPE_Cash through the bank', 'REGION_POPULATION_RELATIVE', 'PRODUCT_COMBINATION_Cash X-Sell: low_MEAN', 'NAME_YIELD_GROUP_low_normal_MAX', 'DAYS_FIRST_DRAWING', 'AMT_GOODS_PRICE_x', 'RATE_DOWN_PAYMENT_MAX', 'HOUSETYPE_MODE_block of flats', 'NAME_YIELD_GROUP_low_normal_MEAN', 'DAYS_FIRST_DRAWING_SUM', 'RATE_DOWN_PAYMENT_SUM', 'EMERGENCYSTATE_MODE_No', 'CNT_INSTALMENT_MATURE_CUM_SUMS', 'FLOORSMAX_MODE', 'FLOORSMAX_MEDI', 'FLOORSMAX_AVG', 'AMT_CREDIT_LIMIT_ACTUAL_SUMS', 'DAYS_EMPLOYED_ANOM', 'NAME_INCOME_TYPE_Pensioner', 'DAYS_FIRST_DRAWING_MEAN', 'CODE_GENDER_F', 'NAME_EDUCATION_TYPE_Higher education', 'CC_COUNT', 'CODE_REJECT_REASON_XAP', 'NAME_CONTRACT_STATUS_1_MEAN', 'NAME_CONTRACT_STATUS_1', 'CODE_REJECT_REASON_XAP_MEAN', 'EXT_SOURCE_1', 'EXT_SOURCE_2', 'EXT_SOURCE_3', 'EXT_SOURCE_1_3_PRODUCT', 'EXT_SOURCE_1_2_3_PRODUCT', 'EXT_SOURCE_1_3_ADD', 'NAME_CONTRACT_STATUS', 'NAME_GOODS_CATEGORY_House Construction_MEAN', 'NAME_GOODS_CATEGORY_House Construction_SUM', 'NAME_GOODS_CATEGORY_Animals', 'NAME_GOODS_CATEGORY_House Construction', 'FLAG_LAST_APPL_PER_CONTRACT_Y_MAX', 'NAME_GOODS_CATEGORY_House Construction_MAX']

In [19]:
print('\nMost Negative Correlations:\n', correlations.head(100))

Most Negative Correlations:
 TARGET                                               1.000000
AMT_BALANCE_CREDIT_RATIO_MEANS                       0.135560
CNT_DRAWINGS_ATM_CURRENT_MEANS                       0.107692
AMT_DRAWINGS_CURRENT_RATIO_MEANS                     0.098962
AMT_DRAWINGS_ATM_CURRENT_RATIO_MEANS                 0.090357
DAYS_CREDIT_mean                                     0.089729
AMT_BALANCE_MEANS                                    0.087177
AMT_TOTAL_RECEIVABLE_MEANS                           0.086490
AMT_RECIVABLE_MEANS                                  0.086478
AMT_RECEIVABLE_PRINCIPAL_MEANS                       0.086062
CNT_DRAWINGS_CURRENT_MEANS                           0.082520
DAYS_BIRTH                                           0.078239
NAME_CONTRACT_STATUS_0_MEAN                          0.077671
DAYS_EMPLOYED                                        0.074958
AMT_INST_MIN_REGULARITY_MEANS                        0.073724
DAYS_CREDIT_UPDATE_mean                              0.068927
NAME_CONTRACT_STATUS_0                               0.064930
NAME_CONTRACT_STATUS_0_SUM                           0.064469
CODE_REJECT_REASON_SCOFR_MAX                         0.063657
NAME_PRODUCT_TYPE_walk-in_SUM                        0.062628
MONTHS_BALANCE_MEANS                                 0.062081
REGION_RATING_CLIENT_W_CITY                          0.060893
AMT_DRAWINGS_ATM_CURRENT_MEANS                       0.059925
MONTHS_BALANCE_SUMS                                  0.059051
REGION_RATING_CLIENT                                 0.058899
AMT_DRAWINGS_CURRENT_MEANS                           0.058732
NAME_PRODUCT_TYPE_walk-in_MAX                        0.058499
NAME_INCOME_TYPE_Working                             0.057481
NAME_PRODUCT_TYPE_walk-in_MEAN                       0.057412
NAME_CONTRACT_STATUS_0_MAX                           0.056291
CODE_REJECT_REASON_SCOFR_SUM                         0.056284
CODE_REJECT_REASON_SCOFR_MEAN                        0.055865
DAYS_LAST_PHONE_CHANGE                               0.055218
CODE_GENDER_M                                        0.054713
CODE_REJECT_REASON_HC_MEAN                           0.054531
DAYS_CREDIT_ENDDATE_sum                              0.053735
DAYS_ENDDATE_FACT_mean                               0.053200
CNT_DRAWINGS_POS_CURRENT_MEANS                       0.052547
DAYS_ID_PUBLISH                                      0.051457
REG_CITY_NOT_WORK_CITY                               0.050994
CNT_DRAWINGS_CURRENT_SUMS                            0.050685
CNT_DRAWINGS_ATM_CURRENT_SUMS                        0.049970
NAME_EDUCATION_TYPE_Secondary / secondary special    0.049824
DAYS_ENDDATE_FACT_sum                                0.048854
PRODUCT_COMBINATION_Card Street_SUM                  0.047953
CODE_REJECT_REASON_HC_MAX                            0.047249
CODE_REJECT_REASON_HC_SUM                            0.047067
DAYS_CREDIT_ENDDATE_mean                             0.046983
DAYS_DECISION_MEAN                                   0.046864
NAME_CLIENT_TYPE_New_SUM                             0.046048
FLAG_EMP_PHONE                                       0.045982
NAME_CONTRACT_TYPE_Revolving loans_SUM               0.045602
REG_CITY_NOT_LIVE_CITY                               0.044395
FLAG_DOCUMENT_3                                      0.044346
CODE_REJECT_REASON_LIMIT_MAX                         0.044054
DAYS_ENTRY_PAYMENT_MEANS                             0.043992
DAYS_INSTALMENT_MEANS                                0.043509
NAME_CLIENT_TYPE_New_MAX                             0.043429
OCCUPATION_TYPE_Laborers                             0.043019
DAYS_CREDIT_sum                                      0.042000
DAYS_REGISTRATION                                    0.041975
NAME_PORTFOLIO_Cards_SUM                             0.041480
DAYS_CREDIT_UPDATE_sum                               0.041404
MONTHS_BALANCE_SUM                                   0.040570
PRODUCT_COMBINATION_Card Street_MAX                  0.040522
CODE_REJECT_REASON_LIMIT_SUM                         0.040503
NAME_PRODUCT_TYPE_walk-in                            0.040310
PRODUCT_COMBINATION_Card Street_MEAN                 0.040242
DAYS_DECISION                                        0.040164
CODE_REJECT_REASON_LIMIT_MEAN                        0.039842
NAME_CONTRACT_TYPE_Revolving loans_MEAN              0.038723
CNT_DRAWINGS_POS_CURRENT_SUMS                        0.038457
AMT_DRAWINGS_ATM_CURRENT_SUMS                        0.038106
OWN_CAR_AGE                                          0.037612
NAME_YIELD_GROUP_high_MEAN                           0.037568
NAME_YIELD_GROUP_high_SUM                            0.036931
NAME_CONTRACT_TYPE_Revolving loans_MAX               0.036462
PRODUCT_COMBINATION_Cash X-Sell: high_SUM            0.036291
PRODUCT_COMBINATION_Cash X-Sell: high_MAX            0.036279
PRODUCT_COMBINATION_Cash Street: high_MAX            0.036275
NAME_CASH_LOAN_PURPOSE_Repairs_MAX                   0.035257
DAYS_ENTRY_PAYMENT_SUMS                              0.035227
DAYS_INSTALMENT_SUMS                                 0.035064
NAME_PORTFOLIO_Cards_MAX                             0.035032
CHANNEL_TYPE_AP+ (Cash loan)_MEAN                    0.034828
CHANNEL_TYPE_AP+ (Cash loan)_SUM                     0.034715
MONTHS_BALANCE_MEAN                                  0.034543
NAME_YIELD_GROUP_high_MAX                            0.033986
CHANNEL_TYPE_AP+ (Cash loan)_MAX                     0.032869
DAYS_LAST_DUE                                        0.032807
CODE_REJECT_REASON_HC                                0.032793
DAYS_LAST_DUE_1ST_VERSION                            0.032637
LIVE_CITY_NOT_WORK_CITY                              0.032518
DEF_30_CNT_SOCIAL_CIRCLE                             0.032248
DAYS_TERMINATION                                     0.031798
PRODUCT_COMBINATION_Cash Street: high_SUM            0.031762
NAME_PORTFOLIO_Cards_MEAN                            0.031726
NAME_CASH_LOAN_PURPOSE_Repairs_SUM                   0.031490
RATE_INTEREST_PRIVILEGED_MAX                         0.031419
DEF_60_CNT_SOCIAL_CIRCLE                             0.031276
Name: TARGET, dtype: float64

In [27]:
neg_list = [x[0] for x in correlations.head(100).items()]

In [28]:
neg_list

['TARGET',
 'AMT_BALANCE_CREDIT_RATIO_MEANS',
 'CNT_DRAWINGS_ATM_CURRENT_MEANS',
 'AMT_DRAWINGS_CURRENT_RATIO_MEANS',
 'AMT_DRAWINGS_ATM_CURRENT_RATIO_MEANS',
 'DAYS_CREDIT_mean',
 'AMT_BALANCE_MEANS',
 'AMT_TOTAL_RECEIVABLE_MEANS',
 'AMT_RECIVABLE_MEANS',
 'AMT_RECEIVABLE_PRINCIPAL_MEANS',
 'CNT_DRAWINGS_CURRENT_MEANS',
 'DAYS_BIRTH',
 'NAME_CONTRACT_STATUS_0_MEAN',
 'DAYS_EMPLOYED',
 'AMT_INST_MIN_REGULARITY_MEANS',
 'DAYS_CREDIT_UPDATE_mean',
 'NAME_CONTRACT_STATUS_0',
 'NAME_CONTRACT_STATUS_0_SUM',
 'CODE_REJECT_REASON_SCOFR_MAX',
 'NAME_PRODUCT_TYPE_walk-in_SUM',
 'MONTHS_BALANCE_MEANS',
 'REGION_RATING_CLIENT_W_CITY',
 'AMT_DRAWINGS_ATM_CURRENT_MEANS',
 'MONTHS_BALANCE_SUMS',
 'REGION_RATING_CLIENT',
 'AMT_DRAWINGS_CURRENT_MEANS',
 'NAME_PRODUCT_TYPE_walk-in_MAX',
 'NAME_INCOME_TYPE_Working',
 'NAME_PRODUCT_TYPE_walk-in_MEAN',
 'NAME_CONTRACT_STATUS_0_MAX',
 'CODE_REJECT_REASON_SCOFR_SUM',
 'CODE_REJECT_REASON_SCOFR_MEAN',
 'DAYS_LAST_PHONE_CHANGE',
 'CODE_GENDER_M',
 'CODE_REJECT_REASON_HC_MEAN',
 'DAYS_CREDIT_ENDDATE_sum',
 'DAYS_ENDDATE_FACT_mean',
 'CNT_DRAWINGS_POS_CURRENT_MEANS',
 'DAYS_ID_PUBLISH',
 'REG_CITY_NOT_WORK_CITY',
 'CNT_DRAWINGS_CURRENT_SUMS',
 'CNT_DRAWINGS_ATM_CURRENT_SUMS',
 'NAME_EDUCATION_TYPE_Secondary / secondary special',
 'DAYS_ENDDATE_FACT_sum',
 'PRODUCT_COMBINATION_Card Street_SUM',
 'CODE_REJECT_REASON_HC_MAX',
 'CODE_REJECT_REASON_HC_SUM',
 'DAYS_CREDIT_ENDDATE_mean',
 'DAYS_DECISION_MEAN',
 'NAME_CLIENT_TYPE_New_SUM',
 'FLAG_EMP_PHONE',
 'NAME_CONTRACT_TYPE_Revolving loans_SUM',
 'REG_CITY_NOT_LIVE_CITY',
 'FLAG_DOCUMENT_3',
 'CODE_REJECT_REASON_LIMIT_MAX',
 'DAYS_ENTRY_PAYMENT_MEANS',
 'DAYS_INSTALMENT_MEANS',
 'NAME_CLIENT_TYPE_New_MAX',
 'OCCUPATION_TYPE_Laborers',
 'DAYS_CREDIT_sum',
 'DAYS_REGISTRATION',
 'NAME_PORTFOLIO_Cards_SUM',
 'DAYS_CREDIT_UPDATE_sum',
 'MONTHS_BALANCE_SUM',
 'PRODUCT_COMBINATION_Card Street_MAX',
 'CODE_REJECT_REASON_LIMIT_SUM',
 'NAME_PRODUCT_TYPE_walk-in',
 'PRODUCT_COMBINATION_Card Street_MEAN',
 'DAYS_DECISION',
 'CODE_REJECT_REASON_LIMIT_MEAN',
 'NAME_CONTRACT_TYPE_Revolving loans_MEAN',
 'CNT_DRAWINGS_POS_CURRENT_SUMS',
 'AMT_DRAWINGS_ATM_CURRENT_SUMS',
 'OWN_CAR_AGE',
 'NAME_YIELD_GROUP_high_MEAN',
 'NAME_YIELD_GROUP_high_SUM',
 'NAME_CONTRACT_TYPE_Revolving loans_MAX',
 'PRODUCT_COMBINATION_Cash X-Sell: high_SUM',
 'PRODUCT_COMBINATION_Cash X-Sell: high_MAX',
 'PRODUCT_COMBINATION_Cash Street: high_MAX',
 'NAME_CASH_LOAN_PURPOSE_Repairs_MAX',
 'DAYS_ENTRY_PAYMENT_SUMS',
 'DAYS_INSTALMENT_SUMS',
 'NAME_PORTFOLIO_Cards_MAX',
 'CHANNEL_TYPE_AP+ (Cash loan)_MEAN',
 'CHANNEL_TYPE_AP+ (Cash loan)_SUM',
 'MONTHS_BALANCE_MEAN',
 'NAME_YIELD_GROUP_high_MAX',
 'CHANNEL_TYPE_AP+ (Cash loan)_MAX',
 'DAYS_LAST_DUE',
 'CODE_REJECT_REASON_HC',
 'DAYS_LAST_DUE_1ST_VERSION',
 'LIVE_CITY_NOT_WORK_CITY',
 'DEF_30_CNT_SOCIAL_CIRCLE',
 'DAYS_TERMINATION',
 'PRODUCT_COMBINATION_Cash Street: high_SUM',
 'NAME_PORTFOLIO_Cards_MEAN',
 'NAME_CASH_LOAN_PURPOSE_Repairs_SUM',
 'RATE_INTEREST_PRIVILEGED_MAX',
 'DEF_60_CNT_SOCIAL_CIRCLE']

In [32]:
all_list = pos_list+neg_list

In [55]:
all_list.append('SK_ID_CURR')

In [56]:
corr_pd = pd.read_csv(train_file, usecols=all_list,)
corr_pd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307511 entries, 0 to 307510
Columns: 201 entries, SK_ID_CURR to PRODUCT_COMBINATION_POS industry with interest_MAX
dtypes: bool(1), float64(174), int64(25), object(1)
memory usage: 469.5+ MB

1 hot encoding object

In [57]:
corr_pd = pd.get_dummies(corr_pd)

In [58]:
corr_pd.head()

,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_CREDIT_x,AMT_GOODS_PRICE_x,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,...,PRODUCT_COMBINATION_POS household without interest_MAX,PRODUCT_COMBINATION_POS industry with interest_MAX,NAME_CONTRACT_STATUS_Active,NAME_CONTRACT_STATUS_Approved,NAME_CONTRACT_STATUS_Canceled,NAME_CONTRACT_STATUS_Completed,NAME_CONTRACT_STATUS_Demand,NAME_CONTRACT_STATUS_Returned to the store,NAME_CONTRACT_STATUS_Signed,NAME_CONTRACT_STATUS_XNA
0,100002,0,406597.5,351000.0,0.018801,-9461,-637.0,-3648.0,-2120,NaN,...,0.0,0.0,1,0,0,0,0,0,0,0
1,100003,0,1293502.5,1129500.0,0.003541,-16765,-1188.0,-1186.0,-291,NaN,...,0.0,1.0,0,0,0,1,0,0,0,0
2,100004,1,135000.0,135000.0,0.010032,-19046,-225.0,-4260.0,-2531,26.0,...,0.0,0.0,0,0,0,1,0,0,0,0
3,100006,0,312682.5,297000.0,0.008019,-19005,-3039.0,-9833.0,-2437,NaN,...,0.0,1.0,0,0,0,0,0,1,0,0
4,100007,0,513000.0,513000.0,0.028663,-19932,-3038.0,-4311.0,-3458,NaN,...,0.0,0.0,0,0,0,0,0,0,1,0

In [59]:
corr_pd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307511 entries, 0 to 307510
Columns: 208 entries, SK_ID_CURR to NAME_CONTRACT_STATUS_XNA
dtypes: bool(1), float64(174), int64(25), uint8(8)
memory usage: 469.5 MB

Exaggreate data by multiplying columns by themselves

In [60]:
exagg_id_target = corr_pd[['SK_ID_CURR', 'TARGET']]

In [61]:
corr_pd.drop(columns=['SK_ID_CURR', 'TARGET'], inplace=True)
exaggerated = corr_pd.multiply(corr_pd)

/usr/local/lib/python3.6/dist-packages/pandas/core/computation/expressions.py:180: UserWarning: evaluating in Python space because the '*' operator is not supported by numexpr for the bool dtype, use '&' instead
  .format(op=op_str, alt_op=unsupported[op_str]))

In [62]:
exaggerated.head()

,NAME_CONTRACT_TYPE,AMT_CREDIT_x,AMT_GOODS_PRICE_x,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_EMP_PHONE,...,PRODUCT_COMBINATION_POS household without interest_MAX,PRODUCT_COMBINATION_POS industry with interest_MAX,NAME_CONTRACT_STATUS_Active,NAME_CONTRACT_STATUS_Approved,NAME_CONTRACT_STATUS_Canceled,NAME_CONTRACT_STATUS_Completed,NAME_CONTRACT_STATUS_Demand,NAME_CONTRACT_STATUS_Returned to the store,NAME_CONTRACT_STATUS_Signed,NAME_CONTRACT_STATUS_XNA
0,0,1.653215e+11,1.232010e+11,0.000353,89510521,405769.0,13307904.0,4494400,NaN,1,...,0.0,0.0,1,0,0,0,0,0,0,0
1,0,1.673149e+12,1.275770e+12,0.000013,281065225,1411344.0,1406596.0,84681,NaN,1,...,0.0,1.0,0,0,0,1,0,0,0,0
2,1,1.822500e+10,1.822500e+10,0.000101,362750116,50625.0,18147600.0,6405961,676.0,1,...,0.0,0.0,0,0,0,1,0,0,0,0
3,0,9.777035e+10,8.820900e+10,0.000064,361190025,9235521.0,96687889.0,5938969,NaN,1,...,0.0,1.0,0,0,0,0,0,1,0,0
4,0,2.631690e+11,2.631690e+11,0.000822,397284624,9229444.0,18584721.0,11957764,NaN,1,...,0.0,0.0,0,0,0,0,0,0,1,0

In [64]:
exaggerated = pd.merge(exagg_id_target,exaggerated, left_index=True, right_index=True)

In [67]:
exaggerated.head(100)

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,AMT_CREDIT_x,AMT_GOODS_PRICE_x,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,...,PRODUCT_COMBINATION_POS household without interest_MAX,PRODUCT_COMBINATION_POS industry with interest_MAX,NAME_CONTRACT_STATUS_Active,NAME_CONTRACT_STATUS_Approved,NAME_CONTRACT_STATUS_Canceled,NAME_CONTRACT_STATUS_Completed,NAME_CONTRACT_STATUS_Demand,NAME_CONTRACT_STATUS_Returned to the store,NAME_CONTRACT_STATUS_Signed,NAME_CONTRACT_STATUS_XNA
0,100002,1,0,1.653215e+11,1.232010e+11,0.000353,89510521,405769.0,13307904.0,4494400,...,0.0,0.0,1,0,0,0,0,0,0,0
1,100003,0,0,1.673149e+12,1.275770e+12,0.000013,281065225,1411344.0,1406596.0,84681,...,0.0,1.0,0,0,0,1,0,0,0,0
2,100004,0,1,1.822500e+10,1.822500e+10,0.000101,362750116,50625.0,18147600.0,6405961,...,0.0,0.0,0,0,0,1,0,0,0,0
3,100006,0,0,9.777035e+10,8.820900e+10,0.000064,361190025,9235521.0,96687889.0,5938969,...,0.0,1.0,0,0,0,0,0,1,0,0
4,100007,0,0,2.631690e+11,2.631690e+11,0.000822,397284624,9229444.0,18584721.0,11957764,...,0.0,0.0,0,0,0,0,0,0,1,0
5,100008,0,0,2.405858e+11,2.065702e+11,0.001281,286997481,2521744.0,24700900.0,227529,...,0.0,0.0,0,0,0,0,0,0,1,0
6,100009,0,0,2.435866e+12,1.946025e+12,0.001281,189833284,9796900.0,1471369.0,383161,...,1.0,0.0,0,0,0,1,0,0,0,0
7,100010,0,0,2.340900e+12,2.340900e+12,0.000010,355322500,201601.0,21132409.0,5659641,...,0.0,0.0,0,0,0,1,0,0,0,0
8,100011,0,0,1.039605e+12,8.344822e+11,0.000347,403969801,NaN,55160329.0,12348196,...,0.0,0.0,0,0,0,1,0,0,0,0
9,100012,0,1,1.640250e+11,1.640250e+11,0.000388,209351961,4076361.0,208426969.0,15936064,...,0.0,0.0,0,0,0,1,0,0,0,0
10,100014,0,0,4.257562e+11,4.257562e+11,0.000520,103978809,461041.0,19598329.0,544644,...,1.0,0.0,0,0,0,1,0,0,0,0
11,100015,0,0,2.201217e+10,1.822500e+10,0.000232,416853889,NaN,27520516.0,6310144,...,0.0,1.0,0,0,0,1,0,0,0,0
12,100016,0,0,6.539148e+09,4.556250e+09,0.000982,180606721,7382089.0,96721.0,10413529,...,0.0,1.0,0,0,0,1,0,0,0,0
13,100017,0,0,8.435835e+11,4.865062e+11,0.000276,198415396,9168784.0,413449.0,24117921,...,0.0,0.0,0,0,0,1,0,0,0,0
14,100018,0,0,5.985815e+11,4.617202e+11,0.000100,212663889,41209.0,378225.0,4227136,...,0.0,1.0,0,0,0,1,0,0,0,0
15,100019,0,0,8.986325e+10,6.125625e+10,0.000429,76177984,1338649.0,12208036.0,1871424,...,0.0,0.0,0,0,0,1,0,0,0,0
16,100020,0,0,2.596947e+11,1.497690e+11,0.000347,167210761,1734489.0,40857664.0,14945956,...,0.0,0.0,0,0,0,1,0,0,0,0
17,100021,0,1,7.290000e+10,7.290000e+10,0.000120,95570176,36481.0,17164449.0,5890329,...,0.0,0.0,0,0,0,1,0,0,0,0
18,100022,0,1,2.480625e+10,2.480625e+10,0.002136,313927524,60902416.0,76580001.0,1585081,...,0.0,0.0,1,0,0,0,0,0,0,0
19,100023,0,0,2.964704e+11,2.065702e+11,0.000232,128777104,4153444.0,1042441.0,15713296,...,1.0,0.0,0,0,0,1,0,0,0,0
20,100024,0,1,1.827562e+11,1.827562e+11,0.000232,333135504,18369796.0,88804.0,3240000,...,NaN,NaN,0,0,0,0,0,0,0,0
21,100025,0,0,1.282723e+12,8.593290e+11,0.000633,219484225,2729104.0,5285401.0,5285401,...,1.0,0.0,0,0,0,1,0,0,0,0
22,100026,0,0,2.475262e+11,2.025000e+11,0.000429,124233316,18541636.0,12996.0,6340324,...,1.0,0.0,0,0,0,1,0,0,0,0
23,100027,0,0,5.752802e+10,5.062500e+10,0.000040,616379929,NaN,81216144.0,13571856,...,0.0,0.0,0,0,0,1,0,0,0,0
24,100029,0,0,6.125625e+10,6.125625e+10,0.000697,127373796,556516.0,11664.0,13905441,...,0.0,1.0,0,0,0,1,0,0,0,0
25,100030,0,0,5.062500e+10,5.062500e+10,0.000822,373803556,12208036.0,5851561.0,8369449,...,0.0,1.0,0,0,0,1,0,0,0,0
26,100031,1,0,9.603843e+11,4.928040e+11,0.000325,350588176,6906384.0,43204329.0,3337929,...,NaN,NaN,0,0,0,0,0,0,0,0
27,100032,0,0,1.069447e+11,7.290000e+10,0.000365,254338704,1522756.0,33431524.0,9941409,...,0.0,0.0,0,0,0,1,0,0,0,0
28,100033,0,0,6.254121e+11,4.556250e+11,0.002136,99880036,3225616.0,21790224.0,7080921,...,0.0,0.0,0,0,0,1,0,0,0,0
29,100034,0,1,3.240000e+10,3.240000e+10,0.000946,106936281,1020100.0,23030401.0,9090225,...,0.0,0.0,0,0,0,1,0,0,0,0
30,100035,0,0,4.434122e+11,2.275290e+11,0.000633,233478400,7118224.0,27730756.0,14341369,...,0.0,1.0,0,0,0,0,0,0,1,0
31,100036,0,0,2.622095e+11,1.296000e+11,0.000074,124188736,1218816.0,61559716.0,8433216,...,1.0,0.0,1,0,0,0,0,0,0,0
32,100037,0,0,3.960418e+10,3.240000e+10,0.000101,168324676,19395216.0,50737129.0,19927296,...,1.0,0.0,0,0,0,1,0,0,0,0
33,100039,0,0,5.377516e+11,4.617202e+11,0.000232,136749636,4243600.0,12652249.0,12652249,...,0.0,0.0,0,0,0,1,0,0,0,0
34,100040,0,0,1.265625e+12,1.265625e+12,0.000388,255904009,21022225.0,32890225.0,16540489,...,0.0,1.0,0,0,0,1,0,0,0,0
35,100041,0,0,2.025000e+11,2.025000e+11,0.000074,147816964,1625625.0,39250225.0,4036081,...,0.0,0.0,0,0,0,1,0,0,0,0
36,100043,0,0,4.111035e+11,3.063622e+11,0.000355,295805601,589824.0,3969.0,540225,...,0.0,1.0,0,0,0,1,0,0,0,0
37,100044,0,0,2.065702e+11,2.065702e+11,0.000946,444239929,1658944.0,29964676.0,18232900,...,0.0,1.0,0,0,0,1,0,0,0,0
38,100045,0,0,6.114493e+10,5.062500e+10,0.000039,572166400,NaN,96373489.0,24690961,...,0.0,0.0,0,0,0,1,0,0,0,0
39,100046,0,1,2.916000e+11,2.916000e+11,0.000633,260047876,3101121.0,67831696.0,18421264,...,0.0,0.0,1,0,0,0,0,0,0,0
40,100047,1,0,1.424633e+12,7.310250e+11,0.000633,305620324,1592644.0,1397124.0,1058841,...,0.0,0.0,0,0,0,1,0,0,0,0
41,100048,0,0,3.649996e+11,2.916000e+11,0.000084,288014841,225625.0,9909904.0,263169,...,0.0,0.0,0,0,0,1,0,0,0,0
42,100049,1,0,8.344761e+10,5.688225e+10,0.000053,179131456,12938409.0,2025.0,19439281,...,0.0,0.0,0,0,0,1,0,0,0,0
43,100050,0,0,5.569338e+11,4.556250e+11,0.000120,554508304,NaN,33005025.0,20939776,...,0.0,0.0,1,0,0,0,0,0,0,0
44,100051,0,0,4.378502e+11,3.582022e+11,0.000051,96569929,574564.0,17355556.0,5664400,...,1.0,0.0,1,0,0,0,0,0,0,0
45,100052,0,1,3.240000e+10,3.240000e+10,0.000087,63584676,801025.0,43441281.0,412164,...,0.0,0.0,0,0,0,1,0,0,0,0
46,100053,0,0,9.316016e+10,6.350400e+10,0.000388,415059129,NaN,60217600.0,3972049,...,0.0,0.0,0,0,0,1,0,0,0,0
47,100054,0,0,6.793321e+10,5.062500e+10,0.000512,404854641,28430224.0,84584809.0,10778089,...,0.0,0.0,0,0,0,1,0,0,0,0
48,100055,0,0,1.822500e+12,1.822500e+12,0.000429,389154529,19456921.0,38750625.0,10233601,...,0.0,0.0,0,0,0,1,0,0,0,0
49,100056,0,0,2.270494e+12,1.822500e+12,0.000100,333573696,90687529.0,30294016.0,3229209,...,0.0,0.0,0,0,0,0,0,0,1,0
50,100058,0,1,1.822500e+10,1.822500e+10,0.000211,153908836,1382976.0,1320201.0,6635776,...,NaN,NaN,0,0,0,0,0,0,0,0
51,100059,0,0,4.556250e+11,4.556250e+11,0.000697,347151424,48678529.0,15241216.0,3751969,...,1.0,1.0,0,0,0,1,0,0,0,0
52,100060,0,0,2.065702e+11,2.065702e+11,0.000822,150847524,605284.0,3326976.0,3968064,...,0.0,0.0,0,0,0,1,0,0,0,0
53,100061,0,0,9.863054e+10,5.688225e+10,0.000044,109683729,1937664.0,4100625.0,1537600,...,0.0,0.0,0,0,0,1,0,0,0,0
54,100062,0,0,4.556250e+11,4.556250e+11,0.000100,346369321,NaN,48108096.0,4588164,...,0.0,0.0,0,0,0,0,0,0,1,0
55,100063,0,0,7.012848e+11,4.435560e+11,0.000512,167832025,16859236.0,49758916.0,26666896,...,1.0,0.0,0,0,0,1,0,0,0,0
56,100064,0,0,8.923842e+10,4.100625e+10,0.000365,467467641,NaN,4076361.0,1806336,...,1.0,0.0,1,0,0,0,0,0,0,0
57,100068,0,1,6.125625e+10,6.125625e+10,0.000982,332989504,5527201.0,19140625.0,2961841,...,0.0,0.0,0,0,0,0,0,0,1,0
58,100069,0,0,4.101864e+11,2.678062e+11,0.000054,201242596,3038049.0,4528384.0,24820324,...,1.0,1.0,0,0,0,1,0,0,0,0
59,100070,0,0,1.507742e+12,1.275770e+12,0.001060,422055936,4372281.0,46867716.0,320356,...,0.0,0.0,0,0,0,1,0,0,0,0
60,100071,0,0,2.768854e+12,2.523332e+12,0.000353,404854641,5982916.0,45630025.0,4739329,...,1.0,0.0,0,0,0,1,0,0,0,0
61,100072,0,0,1.166400e+12,1.166400e+12,0.000100,62520649,1752976.0,20766249.0,343396,...,1.0,0.0,0,0,0,1,0,0,0,0
62,100073,0,0,1.278618e+12,6.561000e+11,0.000355,521802649,NaN,1085764.0,15737089,...,1.0,1.0,0,0,0,1,0,0,0,0
63,100075,0,0,9.204484e+09,8.100000e+09,0.000025,149817600,13838400.0,27520516.0,20620681,...,0.0,0.0,0,0,0,1,0,0,0,0
64,100076,0,0,9.922500e+10,9.922500e+10,0.000822,192265956,6482116.0,29680704.0,16785409,...,NaN,NaN,0,0,0,0,0,0,0,0
65,100077,0,0,1.578541e+12,8.100000e+11,0.005257,145178401,335241.0,37271025.0,1,...,0.0,0.0,0,0,0,1,0,0,0,0
66,100078,0,0,1.071225e+12,1.071225e+12,0.000822,382202500,23580736.0,46730896.0,9511056,...,0.0,0.0,0,0,0,0,0,0,1,0
67,100079,0,1,7.290000e+10,7.290000e+10,0.000054,235898881,12996.0,25765776.0,8538084,...,0.0,0.0,0,0,0,1,0,0,0,0
68,100080,0,1,2.025000e+11,2.025000e+11,0.000120,142945936,9947716.0,65901924.0,17164449,...,0.0,0.0,0,0,0,1,0,0,0,0
69,100081,0,0,2.025000e+11,2.025000e+11,0.000211,117679104,14641.0,23126481.0,12208036,...,0.0,0.0,0,0,0,1,0,0,0,0
70,100082,0,0,2.025000e+11,2.025000e+11,0.000355,144216081,8088336.0,1896129.0,13366336,...,0.0,0.0,0,0,0,1,0,0,0,0
71,100083,0,0,3.290497e+11,2.148322e+11,0.000093,237344836,795664.0,116281.0,17438976,...,0.0,0.0,0,0,0,0,0,0,1,0
72,100084,0,0,2.453726e+11,2.106810e+11,0.000606,220819600,1336336.0,529.0,1149184,...,0.0,1.0,0,0,0,0,0,0,1,0
73,100085,0,0,5.703119e+11,4.556250e+11,0.000276,125148969,4946176.0,10582009.0,13860729,...,0.0,0.0,0,0,0,1,0,0,0,0
74,100086,0,0,4.556250e+11,4.556250e+11,0.000365,203461696,6210064.0,18722929.0,20403289,...,0.0,0.0,0,0,0,1,0,0,0,0
75,100087,0,0,1.659846e+12,1.265625e+12,0.000009,307721764,4044121.0,2337841.0,976144,...,0.0,1.0,0,0,0,1,0,0,0,0
76,100088,0,1,1.822500e+10,1.822500e+10,0.000520,378964089,16532356.0,21372129.0,8850625,...,0.0,1.0,0,0,0,1,0,0,0,0
77,100089,0,0,1.140825e+11,6.579225e+10,0.000633,93431556,7901721.0,19686969.0,5484964,...,0.0,0.0,0,0,0,1,0,0,0,0
78,100093,0,0,3.422250e+11,3.422250e+11,0.000822,333172009,519841.0,2893401.0,3164841,...,1.0,1.0,0,0,0,1,0,0,0,0
79,100094,0,0,1.294134e+10,8.100000e+09,0.000946,526014225,NaN,159340129.0,11847364,...,0.0,1.0,0,0,0,0,0,0,1,0
80,100095,0,1,1.822500e+10,1.822500e+10,0.000410,349428249,2056356.0,105165025.0,5022081,...,0.0,0.0,0,0,0,1,0,0,0,0
81,100096,1,0,6.350400e+10,6.350400e+10,0.000822,614742436,NaN,29062881.0,17631601,...,NaN,NaN,0,0,0,0,0,0,0,0
82,100097,0,0,5.779428e+11,4.617202e+11,0.001281,307195729,5963364.0,12250000.0,966289,...,1.0,0.0,0,0,0,1,0,0,0,0
83,100098,0,1,7.290000e+10,7.290000e+10,0.000355,302412100,853776.0,51998521.0,822649,...,0.0,0.0,0,0,0,1,0,0,0,0
84,100099,0,0,5.377516e+11,4.617202e+11,0.000084,530473024,NaN,90364036.0,628849,...,0.0,0.0,0,0,0,1,0,0,0,0
85,100100,0,0,6.342474e+11,4.140922e+11,0.000064,253096281,1196836.0,9821956.0,17472400,...,1.0,0.0,0,0,0,1,0,0,0,0
86,100101,0,0,1.179078e+11,8.037225e+10,0.005257,328987044,938961.0,55071241.0,2825761,...,0.0,0.0,0,0,0,0,0,0,1,0
87,100102,0,0,1.069447e+11,7.290000e+10,0.000606,205091041,36864.0,47789569.0,35307364,...,NaN,NaN,0,0,0,0,0,0,0,0
88,100103,0,0,2.025000e+11,2.025000e+11,0.000084,445716544,2869636.0,36687249.0,16104169,...,0.0,1.0,0,0,0,1,0,0,0,0
89,100104,0,0,2.995855e+11,2.232562e+11,0.000512,344325136,743044.0,45819361.0,4182025,...,1.0,0.0,1,0,0,0,0,0,0,0
90,100105,0,0,5.062500e+10,5.062500e+10,0.000982,392436100,78535044.0,20187049.0,9259849,...,0.0,1.0,0,0,0,0,0,0,1,0
91,100108,0,0,2.970686e+11,2.025000e+11,0.000044,163328400,2002225.0,26481316.0,756900,...,0.0,0.0,0,0,0,0,0,0,1,0
92,100110,0,0,1.392335e+11,1.139062e+11,0.001281,115433536,549081.0,195364.0,5669161,...,0.0,0.0,0,0,0,0,0,1,0,0
93,100111,0,0,7.440098e+11,5.184000e+11,0.000520,109935225,1560001.0,21418384.0,9672100,...,0.0,0.0,0,0,0,0,0,0,1,0
94,100112,1,0,9.090860e+11,8.100000e+11,0.000946,104019601,4060225.0,23059204.0,1077444,...,0.0,0.0,0,0,0,1,0,0,0,0
95,100113,0,0,1.822500e+10,1.822500e+10,0.000822,229128769,63680400.0,84198976.0,20939776,...,0.0,0.0,0,0,0,1,0,0,0,0
96,100114,0,0,8.088336e+10,5.062500e+10,0.000946,115218756,480249.0,62615569.0,1855044,...,0.0,0.0,1,0,0,0,0,0,0,0
97,100115,0,0,9.922500e+10,9.922500e+10,0.000822,236267641,134689.0,9431041.0,17732521,...,0.0,0.0,0,0,0,1,0,0,0,0
98,100116,0,0,8.100000e+11,8.100000e+11,0.000100,217592001,45387169.0,11492100.0,22924944,...,0.0,1.0,0,0,0,1,0,0,0,0
99,100118,0,0,4.556250e+11,4.556250e+11,0.000697,504945841,NaN,47089.0,18688329,...,0.0,1.0,0,0,0,1,0,0,0,0

In [68]:
exaggerated.to_csv("train_exaggreated_data.csv", index=False)

In [80]:
all_list.remove('TARGET')
test_corr_pd = pd.read_csv(test_file, usecols=all_list,)
test_corr_pd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48744 entries, 0 to 48743
Columns: 200 entries, SK_ID_CURR to PRODUCT_COMBINATION_POS industry with interest_MAX
dtypes: bool(1), float64(174), int64(24), object(1)
memory usage: 74.1+ MB

In [81]:
test_corr_pd = pd.get_dummies(test_corr_pd)

In [82]:
test_corr_pd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48744 entries, 0 to 48743
Columns: 205 entries, SK_ID_CURR to NAME_CONTRACT_STATUS_Signed
dtypes: bool(1), float64(174), int64(24), uint8(6)
memory usage: 74.0 MB

In [83]:
test_exagg_id_target = test_corr_pd['SK_ID_CURR']

In [84]:
test_corr_pd.drop(columns=['SK_ID_CURR'], inplace=True)
test_exaggerated = test_corr_pd.multiply(test_corr_pd)

/usr/local/lib/python3.6/dist-packages/pandas/core/computation/expressions.py:180: UserWarning: evaluating in Python space because the '*' operator is not supported by numexpr for the bool dtype, use '&' instead
  .format(op=op_str, alt_op=unsupported[op_str]))

In [85]:
test_exaggerated

,NAME_CONTRACT_TYPE,AMT_CREDIT_x,AMT_GOODS_PRICE_x,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_EMP_PHONE,...,PRODUCT_COMBINATION_Cash X-Sell: high_MAX,PRODUCT_COMBINATION_Cash X-Sell: low_MAX,PRODUCT_COMBINATION_POS household without interest_MAX,PRODUCT_COMBINATION_POS industry with interest_MAX,NAME_CONTRACT_STATUS_Active,NAME_CONTRACT_STATUS_Approved,NAME_CONTRACT_STATUS_Completed,NAME_CONTRACT_STATUS_Demand,NAME_CONTRACT_STATUS_Returned to the store,NAME_CONTRACT_STATUS_Signed
0,0,3.235334e+11,2.025000e+11,0.000355,370216081,5424241.0,26728900.0,659344,NaN,1,...,0.0,0.0,0.0,0.0,0,0,1,0,0,0
1,0,4.962558e+10,3.240000e+10,0.001281,326308096,19971961.0,83137924.0,2634129,NaN,1,...,0.0,0.0,0.0,0.0,0,0,0,0,0,1
2,0,4.399191e+11,3.969000e+11,0.000365,401521444,19873764.0,4730625.0,12271009,25.0,1,...,0.0,0.0,0.0,0.0,0,0,0,0,0,1
3,0,2.480625e+12,2.480625e+12,0.000697,195328576,3481956.0,4000000.0,17707264,NaN,1,...,0.0,0.0,1.0,0.0,0,0,1,0,0,0
4,0,3.912502e+11,3.912502e+11,0.000101,170041600,4800481.0,16000000.0,18164644,256.0,1,...,0.0,0.0,0.0,0.0,0,0,1,0,0,0
5,0,9.210011e+11,6.561000e+11,0.000633,346108816,144216081.0,37405456.0,4108729,100.0,1,...,0.0,0.0,1.0,0.0,0,0,1,0,0,0
6,0,2.492216e+11,1.395022e+11,0.000520,278389225,6656400.0,102515625.0,58081,9.0,1,...,0.0,0.0,1.0,0.0,0,0,0,0,0,1
7,0,3.240000e+10,3.240000e+10,0.000026,90554256,1923769.0,25633969.0,4223025,NaN,1,...,0.0,0.0,0.0,0.0,0,0,1,0,0,0
8,0,1.331491e+11,9.922500e+10,0.002136,162409536,1026169.0,2842596.0,10055241,NaN,1,...,0.0,0.0,0.0,0.0,0,0,0,0,0,1
9,0,2.025000e+09,2.025000e+09,0.000347,108056025,6890625.0,65999376.0,9247681,25.0,1,...,0.0,1.0,0.0,0.0,0,0,1,0,0,0
10,0,4.556250e+11,4.556250e+11,0.000010,560268900,NaN,56100100.0,17106496,NaN,0,...,0.0,0.0,1.0,0.0,0,0,1,0,0,0
11,0,6.844555e+10,4.665600e+10,0.000064,240994576,12638025.0,61355889.0,15880225,NaN,1,...,0.0,1.0,1.0,0.0,0,0,1,0,0,0
12,0,8.778184e+10,5.062500e+10,0.000347,150749284,863041.0,36372961.0,21031396,NaN,1,...,0.0,0.0,0.0,0.0,0,0,1,0,0,0
13,0,1.296000e+11,1.296000e+11,0.000211,387577969,12802084.0,113912929.0,10131489,9.0,1,...,0.0,0.0,0.0,1.0,0,0,0,0,1,0
14,1,2.480625e+10,2.480625e+10,0.000982,146192281,3348900.0,1085764.0,17816841,NaN,1,...,0.0,1.0,0.0,0.0,0,0,1,0,0,0
15,0,8.778184e+10,5.062500e+10,0.001060,183954969,1014049.0,32706961.0,16353936,196.0,1,...,0.0,0.0,0.0,0.0,0,0,1,0,0,0
16,0,1.660726e+11,1.296000e+11,0.000049,375390625,22458121.0,9211225.0,8381025,121.0,1,...,0.0,0.0,0.0,0.0,0,0,1,0,0,0
17,0,2.492216e+11,1.395022e+11,0.000010,515517025,NaN,26081449.0,35880100,225.0,0,...,0.0,0.0,0.0,1.0,0,0,0,0,0,1
18,0,1.860024e+11,1.296000e+11,0.000633,120165444,3545689.0,9801.0,2961841,64.0,1,...,1.0,0.0,0.0,1.0,0,0,1,0,0,0
19,0,2.289608e+11,2.065702e+11,0.000103,322382025,93025.0,101747569.0,2298256,100.0,1,...,0.0,0.0,0.0,0.0,0,0,1,0,0,0
20,0,5.062500e+10,5.062500e+10,0.000053,110397049,7728400.0,25725184.0,7447441,NaN,1,...,1.0,0.0,0.0,0.0,0,0,0,0,0,1
21,0,7.110329e+10,4.100625e+10,0.000136,508818249,176730436.0,173027716.0,17530969,NaN,1,...,0.0,1.0,0.0,0.0,0,0,1,0,0,0
22,0,2.916000e+11,2.916000e+11,0.005257,519110656,NaN,26040609.0,27342441,NaN,0,...,0.0,1.0,1.0,1.0,0,0,1,0,0,0
23,0,1.724527e+12,1.025156e+12,0.000606,142754704,2002225.0,31483321.0,16418704,NaN,1,...,1.0,0.0,0.0,0.0,0,0,1,0,0,0
24,0,2.906288e+11,2.025000e+11,0.000982,173501584,12376324.0,38526849.0,18003049,400.0,1,...,0.0,0.0,0.0,0.0,0,0,1,0,0,0
25,0,5.062500e+10,5.062500e+10,0.000120,236975236,935089.0,29041321.0,29517489,NaN,1,...,0.0,0.0,0.0,0.0,0,0,0,0,0,1
26,0,6.555239e+10,3.240000e+10,0.000388,447322500,NaN,17280649.0,21696964,NaN,0,...,0.0,1.0,1.0,0.0,0,0,1,0,0,0
27,0,2.513649e+11,1.751422e+11,0.000982,442681600,6086089.0,842724.0,13417569,NaN,1,...,0.0,1.0,1.0,0.0,0,0,1,0,0,0
28,0,2.025000e+11,2.025000e+11,0.000025,248787529,1716100.0,51451929.0,25492401,484.0,1,...,0.0,0.0,1.0,0.0,0,0,1,0,0,0
29,0,8.930250e+11,8.930250e+11,0.000946,316697616,7756225.0,5271616.0,1498176,1.0,1,...,0.0,0.0,0.0,1.0,0,0,1,0,0,0
30,0,2.404667e+11,1.604002e+11,0.000025,168844036,4223025.0,26896.0,11978521,NaN,1,...,1.0,1.0,0.0,0.0,0,0,1,0,0,0
31,0,1.126220e+11,7.049025e+10,0.000025,208658025,3066001.0,4857616.0,25492401,NaN,1,...,0.0,1.0,0.0,0.0,0,0,1,0,0,0
32,0,1.860024e+11,1.296000e+11,0.000232,84400969,72900.0,13417569.0,525625,NaN,1,...,NaN,NaN,NaN,NaN,0,0,0,0,0,0
33,0,1.331491e+11,9.922500e+10,0.000276,178623225,1951609.0,32775625.0,33500944,NaN,1,...,NaN,NaN,NaN,NaN,0,0,1,0,0,0
34,0,6.720589e+11,5.184000e+11,0.000120,244328161,9363600.0,2387025.0,9998244,1.0,1,...,0.0,1.0,0.0,0.0,0,0,0,0,0,1
35,0,1.438201e+10,1.265625e+10,0.000365,102515625,1347921.0,57121.0,5452225,361.0,1,...,0.0,0.0,0.0,0.0,0,0,1,0,0,0
36,0,3.240000e+12,3.240000e+12,0.000697,535413321,NaN,68644.0,21501769,0.0,0,...,0.0,1.0,0.0,0.0,0,0,1,0,0,0
37,0,2.025000e+11,2.025000e+11,0.000025,117375556,3193369.0,16313521.0,133225,NaN,1,...,0.0,0.0,0.0,1.0,0,0,0,0,0,1
38,0,2.632106e+11,2.232562e+11,0.002136,205692964,952576.0,5008644.0,1364224,9.0,1,...,0.0,0.0,0.0,0.0,0,0,1,0,0,0
39,0,1.296000e+11,1.296000e+11,0.000101,76440049,64009.0,75898944.0,2005056,NaN,1,...,0.0,0.0,0.0,0.0,0,0,0,0,0,1
40,0,6.125625e+10,6.125625e+10,0.000332,313608681,15288100.0,84529636.0,1600225,NaN,1,...,1.0,1.0,0.0,0.0,0,0,1,0,0,0
41,0,2.148322e+11,2.148322e+11,0.000084,543495969,NaN,3261636.0,27112849,NaN,0,...,0.0,1.0,1.0,0.0,1,0,0,0,0,0
42,0,2.906288e+11,2.025000e+11,0.000429,193210000,5253264.0,94864.0,32228329,441.0,1,...,0.0,0.0,0.0,0.0,0,0,1,0,0,0
43,0,6.275206e+11,3.969000e+11,0.000072,319837456,6937956.0,51509329.0,1117249,169.0,1,...,0.0,0.0,0.0,0.0,0,0,1,0,0,0
44,0,5.325964e+11,3.969000e+11,0.000982,358269184,2418025.0,43758225.0,6036849,9.0,1,...,0.0,0.0,1.0,0.0,0,0,1,0,0,0
45,0,6.380447e+11,4.865062e+11,0.000325,344176704,5880625.0,10850436.0,4393216,NaN,1,...,1.0,1.0,0.0,0.0,0,0,0,0,0,1
46,0,6.812100e+10,6.812100e+10,0.000211,393625600,14145121.0,1755625.0,11042329,196.0,1,...,0.0,0.0,1.0,0.0,0,0,1,0,0,0
47,0,1.860024e+11,1.296000e+11,0.000053,137968516,3254416.0,1199025.0,8473921,484.0,1,...,0.0,0.0,0.0,0.0,0,0,0,0,0,1
48,0,1.296000e+11,1.296000e+11,0.000332,143784081,1697809.0,27899524.0,876096,NaN,1,...,0.0,0.0,0.0,1.0,0,0,1,0,0,0
49,0,2.964802e+11,2.964802e+11,0.000822,157929489,25411681.0,21529600.0,20839225,16.0,1,...,0.0,0.0,1.0,0.0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48694,0,2.678062e+11,2.678062e+11,0.000697,425720689,NaN,45792289.0,17572864,16.0,0,...,0.0,1.0,0.0,0.0,0,0,1,0,0,0
48695,0,2.025000e+11,2.025000e+11,0.000697,476679889,NaN,86508601.0,22581504,NaN,0,...,0.0,0.0,0.0,1.0,0,0,1,0,0,0
48696,0,6.625013e+10,5.688225e+10,0.000106,107661376,2917264.0,18232900.0,5793649,121.0,1,...,0.0,0.0,1.0,0.0,0,0,1,0,0,0
48697,0,1.296000e+11,1.296000e+11,0.000136,215032896,8514724.0,8156736.0,4583881,NaN,1,...,0.0,0.0,0.0,0.0,0,0,0,0,0,1
48698,0,5.062500e+10,5.062500e+10,0.000332,584092224,NaN,48427681.0,17648401,NaN,0,...,0.0,1.0,0.0,1.0,0,0,1,0,0,0
48699,0,3.462911e+11,2.190240e+11,0.000120,84492864,1221025.0,77105961.0,3467044,NaN,1,...,1.0,0.0,0.0,1.0,0,0,1,0,0,0
48700,0,2.065702e+11,2.065702e+11,0.000111,348680929,1934881.0,18139081.0,4915089,NaN,1,...,0.0,0.0,1.0,0.0,1,0,0,0,0,0
48701,0,2.906288e+11,2.025000e+11,0.000606,444619396,NaN,85303696.0,8491396,NaN,0,...,0.0,1.0,0.0,0.0,0,0,1,0,0,0
48702,0,5.618038e+10,3.240000e+10,0.000276,196897024,2601769.0,58293225.0,18062500,9.0,1,...,1.0,0.0,0.0,0.0,0,0,1,0,0,0
48703,0,1.566307e+11,8.037225e+10,0.000982,489427129,NaN,49984900.0,18740241,NaN,0,...,0.0,1.0,0.0,0.0,0,0,1,0,0,0
48704,0,1.822500e+10,1.822500e+10,0.000365,255840025,579121.0,8755681.0,25462116,NaN,1,...,0.0,1.0,1.0,0.0,0,0,1,0,0,0
48705,0,4.556250e+11,4.556250e+11,0.000053,190191681,14424804.0,61246276.0,16032016,NaN,1,...,0.0,0.0,0.0,0.0,0,0,1,0,0,0
48706,0,7.535025e+10,7.535025e+10,0.000232,280964644,129600.0,331776.0,91809,NaN,1,...,1.0,1.0,0.0,0.0,0,0,1,0,0,0
48707,0,5.062500e+10,5.062500e+10,0.000100,103205281,399424.0,12299049.0,8076964,9.0,1,...,0.0,1.0,0.0,0.0,0,0,1,0,0,0
48708,0,6.793321e+10,5.062500e+10,0.000101,135466321,2595321.0,9199089.0,18748900,NaN,1,...,0.0,0.0,0.0,0.0,1,0,0,0,0,0
48709,0,1.029909e+11,8.037225e+10,0.000982,80102500,1990921.0,79637776.0,2673225,196.0,1,...,NaN,NaN,NaN,NaN,0,0,0,0,0,0
48710,0,7.583029e+10,5.062500e+10,0.000053,135419769,20620681.0,26656569.0,14070001,169.0,1,...,0.0,0.0,0.0,0.0,0,0,0,0,0,1
48711,0,1.265625e+12,1.265625e+12,0.000697,262602025,4879681.0,12439729.0,21911761,NaN,1,...,0.0,0.0,0.0,0.0,0,0,1,0,0,0
48712,0,3.597336e+11,2.275290e+11,0.000065,227406400,1258884.0,229441.0,17106496,NaN,1,...,0.0,0.0,1.0,0.0,0,0,1,0,0,0
48713,0,2.445596e+10,1.822500e+10,0.000113,142229476,8836.0,2374681.0,21224449,NaN,1,...,0.0,0.0,1.0,0.0,1,0,0,0,0,0
48714,0,2.995066e+11,2.450250e+11,0.000429,143688169,3045025.0,42849.0,5688225,NaN,1,...,0.0,0.0,0.0,0.0,0,0,1,0,0,0
48715,0,8.100000e+11,8.100000e+11,0.001281,299047849,23386896.0,60512841.0,693889,36.0,1,...,0.0,0.0,0.0,0.0,0,0,1,0,0,0
48716,0,1.015346e+11,4.665600e+10,0.000068,158936449,5212089.0,42680089.0,17994564,NaN,1,...,0.0,0.0,0.0,0.0,0,0,1,0,0,0
48717,0,3.240000e+10,3.240000e+10,0.000946,563207824,NaN,123099025.0,22372900,NaN,0,...,0.0,1.0,0.0,0.0,0,0,1,0,0,0
48718,0,1.296000e+11,1.296000e+11,0.001281,202692169,24314761.0,145161.0,136161,NaN,1,...,0.0,1.0,1.0,0.0,0,0,1,0,0,0
48719,0,4.765327e+11,3.014010e+11,0.000101,113784889,3916441.0,8838729.0,10989225,NaN,1,...,1.0,0.0,0.0,1.0,0,0,0,0,0,1
48720,0,1.046264e+11,7.290000e+10,0.000606,168220900,93025.0,49294441.0,11881,144.0,1,...,0.0,0.0,1.0,1.0,0,0,0,0,0,1
48721,0,2.193358e+11,1.463062e+11,0.001281,65318724,1713481.0,7756225.0,455625,NaN,1,...,0.0,0.0,0.0,0.0,0,0,1,0,0,0
48722,0,2.772225e+10,2.772225e+10,0.000332,272448036,1716100.0,79637776.0,2209,NaN,1,...,0.0,1.0,1.0,0.0,0,0,0,0,0,1
48723,0,9.922500e+10,9.922500e+10,0.000137,226532601,7946761.0,12117361.0,12117361,NaN,1,...,0.0,0.0,0.0,0.0,0,0,1,0,0,0
48724,0,2.649264e+11,1.497690e+11,0.000410,251127409,4800481.0,26977636.0,17147881,NaN,1,...,1.0,0.0,0.0,0.0,0,0,0,0,0,1
48725,0,2.025000e+11,2.025000e+11,0.000429,418775296,13890529.0,58798224.0,16104169,NaN,1,...,0.0,1.0,0.0,0.0,0,0,1,0,0,0
48726,0,1.004683e+12,7.157160e+11,0.000040,279224100,4822416.0,79156609.0,64516,NaN,1,...,0.0,0.0,1.0,0.0,0,0,1,0,0,0
48727,0,2.227735e+10,1.822500e+10,0.000325,252301456,42915601.0,2896804.0,19492225,NaN,1,...,0.0,0.0,1.0,0.0,0,0,1,0,0,0
48728,0,4.697540e+11,3.422250e+11,0.000633,436726404,NaN,69039481.0,17960644,NaN,0,...,0.0,1.0,0.0,0.0,0,0,1,0,0,0
48729,0,1.822500e+10,1.822500e+10,0.000068,173317225,2446096.0,32558436.0,5433561,NaN,1,...,0.0,0.0,0.0,0.0,0,0,0,0,0,1
48730,0,1.981096e+11,1.640250e+11,0.000276,256608361,14130081.0,88078225.0,26214400,121.0,1,...,NaN,NaN,NaN,NaN,0,0,0,0,0,0
48731,0,2.025000e+11,2.025000e+11,0.000232,421727296,NaN,90155025.0,15249025,196.0,0,...,0.0,0.0,1.0,1.0,0,0,1,0,0,0
48732,0,2.301121e+11,2.025000e+11,0.000347,313856656,3594816.0,40678884.0,1540081,NaN,1,...,0.0,0.0,0.0,1.0,0,0,0,0,0,1
48733,0,1.097824e+12,8.181202e+11,0.001281,400120009,13571856.0,93257649.0,12588304,NaN,1,...,0.0,0.0,1.0,0.0,0,0,1,0,0,0
48734,0,6.983711e+11,5.852250e+11,0.000633,129663769,715716.0,87965641.0,6400900,NaN,1,...,0.0,0.0,0.0,0.0,0,0,1,0,0,0
48735,0,1.188274e+10,8.100000e+09,0.000606,528770025,NaN,146119744.0,15904144,NaN,0,...,1.0,1.0,0.0,1.0,0,0,0,0,0,1
48736,0,2.504902e+11,2.025000e+11,0.000045,474368400,NaN,115455025.0,27552001,144.0,0,...,0.0,0.0,0.0,0.0,0,0,1,0,0,0
48737,0,1.296000e+11,1.296000e+11,0.000697,376243609,14161.0,19236996.0,8673025,NaN,1,...,0.0,1.0,1.0,0.0,0,0,1,0,0,0
48738,0,6.351534e+10,4.733301e+10,0.000084,137077264,136161.0,30276.0,17455684,4225.0,1,...,0.0,0.0,1.0,1.0,0,0,1,0,0,0
48739,0,1.702058e+11,7.290000e+10,0.000004,398800900,26718561.0,82700836.0,11553201,NaN,1,...,0.0,0.0,0.0,0.0,0,0,1,0,0,0
48740,0,3.873979e+11,2.450250e+11,0.001281,125126596,1320201.0,9090225.0,9018009,NaN,1,...,1.0,0.0,1.0,0.0,0,0,0,0,0,1
48741,0,9.922500e+10,9.922500e+10,0.000697,253510084,9223369.0,7187761.0,2262016,16.0,1,...,0.0,0.0,0.0,1.0,0,0,1,0,0,0
48742,0,2.025000e+11,2.025000e+11,0.000355,195105024,7458361.0,2134521.0,1860496,NaN,1,...,1.0,0.0,0.0,1.0,0,0,0,0,0,1
48743,0,9.782382e+10,7.290000e+10,0.000044,194937444,400689.0,1149184.0,17808400,484.0,1,...,1.0,1.0,0.0,0.0,0,0,1,0,0,0

In [87]:
test_exaggerated['SK_ID_CURR'] = test_exagg_id_target

In [88]:
test_exaggerated

,NAME_CONTRACT_TYPE,AMT_CREDIT_x,AMT_GOODS_PRICE_x,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_EMP_PHONE,...,PRODUCT_COMBINATION_Cash X-Sell: low_MAX,PRODUCT_COMBINATION_POS household without interest_MAX,PRODUCT_COMBINATION_POS industry with interest_MAX,NAME_CONTRACT_STATUS_Active,NAME_CONTRACT_STATUS_Approved,NAME_CONTRACT_STATUS_Completed,NAME_CONTRACT_STATUS_Demand,NAME_CONTRACT_STATUS_Returned to the store,NAME_CONTRACT_STATUS_Signed,SK_ID_CURR
0,0,3.235334e+11,2.025000e+11,0.000355,370216081,5424241.0,26728900.0,659344,NaN,1,...,0.0,0.0,0.0,0,0,1,0,0,0,100001
1,0,4.962558e+10,3.240000e+10,0.001281,326308096,19971961.0,83137924.0,2634129,NaN,1,...,0.0,0.0,0.0,0,0,0,0,0,1,100005
2,0,4.399191e+11,3.969000e+11,0.000365,401521444,19873764.0,4730625.0,12271009,25.0,1,...,0.0,0.0,0.0,0,0,0,0,0,1,100013
3,0,2.480625e+12,2.480625e+12,0.000697,195328576,3481956.0,4000000.0,17707264,NaN,1,...,0.0,1.0,0.0,0,0,1,0,0,0,100028
4,0,3.912502e+11,3.912502e+11,0.000101,170041600,4800481.0,16000000.0,18164644,256.0,1,...,0.0,0.0,0.0,0,0,1,0,0,0,100038
5,0,9.210011e+11,6.561000e+11,0.000633,346108816,144216081.0,37405456.0,4108729,100.0,1,...,0.0,1.0,0.0,0,0,1,0,0,0,100042
6,0,2.492216e+11,1.395022e+11,0.000520,278389225,6656400.0,102515625.0,58081,9.0,1,...,0.0,1.0,0.0,0,0,0,0,0,1,100057
7,0,3.240000e+10,3.240000e+10,0.000026,90554256,1923769.0,25633969.0,4223025,NaN,1,...,0.0,0.0,0.0,0,0,1,0,0,0,100065
8,0,1.331491e+11,9.922500e+10,0.002136,162409536,1026169.0,2842596.0,10055241,NaN,1,...,0.0,0.0,0.0,0,0,0,0,0,1,100066
9,0,2.025000e+09,2.025000e+09,0.000347,108056025,6890625.0,65999376.0,9247681,25.0,1,...,1.0,0.0,0.0,0,0,1,0,0,0,100067
10,0,4.556250e+11,4.556250e+11,0.000010,560268900,NaN,56100100.0,17106496,NaN,0,...,0.0,1.0,0.0,0,0,1,0,0,0,100074
11,0,6.844555e+10,4.665600e+10,0.000064,240994576,12638025.0,61355889.0,15880225,NaN,1,...,1.0,1.0,0.0,0,0,1,0,0,0,100090
12,0,8.778184e+10,5.062500e+10,0.000347,150749284,863041.0,36372961.0,21031396,NaN,1,...,0.0,0.0,0.0,0,0,1,0,0,0,100091
13,0,1.296000e+11,1.296000e+11,0.000211,387577969,12802084.0,113912929.0,10131489,9.0,1,...,0.0,0.0,1.0,0,0,0,0,1,0,100092
14,1,2.480625e+10,2.480625e+10,0.000982,146192281,3348900.0,1085764.0,17816841,NaN,1,...,1.0,0.0,0.0,0,0,1,0,0,0,100106
15,0,8.778184e+10,5.062500e+10,0.001060,183954969,1014049.0,32706961.0,16353936,196.0,1,...,0.0,0.0,0.0,0,0,1,0,0,0,100107
16,0,1.660726e+11,1.296000e+11,0.000049,375390625,22458121.0,9211225.0,8381025,121.0,1,...,0.0,0.0,0.0,0,0,1,0,0,0,100109
17,0,2.492216e+11,1.395022e+11,0.000010,515517025,NaN,26081449.0,35880100,225.0,0,...,0.0,0.0,1.0,0,0,0,0,0,1,100117
18,0,1.860024e+11,1.296000e+11,0.000633,120165444,3545689.0,9801.0,2961841,64.0,1,...,0.0,0.0,1.0,0,0,1,0,0,0,100128
19,0,2.289608e+11,2.065702e+11,0.000103,322382025,93025.0,101747569.0,2298256,100.0,1,...,0.0,0.0,0.0,0,0,1,0,0,0,100141
20,0,5.062500e+10,5.062500e+10,0.000053,110397049,7728400.0,25725184.0,7447441,NaN,1,...,0.0,0.0,0.0,0,0,0,0,0,1,100150
21,0,7.110329e+10,4.100625e+10,0.000136,508818249,176730436.0,173027716.0,17530969,NaN,1,...,1.0,0.0,0.0,0,0,1,0,0,0,100168
22,0,2.916000e+11,2.916000e+11,0.005257,519110656,NaN,26040609.0,27342441,NaN,0,...,1.0,1.0,1.0,0,0,1,0,0,0,100169
23,0,1.724527e+12,1.025156e+12,0.000606,142754704,2002225.0,31483321.0,16418704,NaN,1,...,0.0,0.0,0.0,0,0,1,0,0,0,100170
24,0,2.906288e+11,2.025000e+11,0.000982,173501584,12376324.0,38526849.0,18003049,400.0,1,...,0.0,0.0,0.0,0,0,1,0,0,0,100171
25,0,5.062500e+10,5.062500e+10,0.000120,236975236,935089.0,29041321.0,29517489,NaN,1,...,0.0,0.0,0.0,0,0,0,0,0,1,100172
26,0,6.555239e+10,3.240000e+10,0.000388,447322500,NaN,17280649.0,21696964,NaN,0,...,1.0,1.0,0.0,0,0,1,0,0,0,100184
27,0,2.513649e+11,1.751422e+11,0.000982,442681600,6086089.0,842724.0,13417569,NaN,1,...,1.0,1.0,0.0,0,0,1,0,0,0,100187
28,0,2.025000e+11,2.025000e+11,0.000025,248787529,1716100.0,51451929.0,25492401,484.0,1,...,0.0,1.0,0.0,0,0,1,0,0,0,100212
29,0,8.930250e+11,8.930250e+11,0.000946,316697616,7756225.0,5271616.0,1498176,1.0,1,...,0.0,0.0,1.0,0,0,1,0,0,0,100222
30,0,2.404667e+11,1.604002e+11,0.000025,168844036,4223025.0,26896.0,11978521,NaN,1,...,1.0,0.0,0.0,0,0,1,0,0,0,100223
31,0,1.126220e+11,7.049025e+10,0.000025,208658025,3066001.0,4857616.0,25492401,NaN,1,...,1.0,0.0,0.0,0,0,1,0,0,0,100232
32,0,1.860024e+11,1.296000e+11,0.000232,84400969,72900.0,13417569.0,525625,NaN,1,...,NaN,NaN,NaN,0,0,0,0,0,0,100241
33,0,1.331491e+11,9.922500e+10,0.000276,178623225,1951609.0,32775625.0,33500944,NaN,1,...,NaN,NaN,NaN,0,0,1,0,0,0,100245
34,0,6.720589e+11,5.184000e+11,0.000120,244328161,9363600.0,2387025.0,9998244,1.0,1,...,1.0,0.0,0.0,0,0,0,0,0,1,100253
35,0,1.438201e+10,1.265625e+10,0.000365,102515625,1347921.0,57121.0,5452225,361.0,1,...,0.0,0.0,0.0,0,0,1,0,0,0,100256
36,0,3.240000e+12,3.240000e+12,0.000697,535413321,NaN,68644.0,21501769,0.0,0,...,1.0,0.0,0.0,0,0,1,0,0,0,100271
37,0,2.025000e+11,2.025000e+11,0.000025,117375556,3193369.0,16313521.0,133225,NaN,1,...,0.0,0.0,1.0,0,0,0,0,0,1,100278
38,0,2.632106e+11,2.232562e+11,0.002136,205692964,952576.0,5008644.0,1364224,9.0,1,...,0.0,0.0,0.0,0,0,1,0,0,0,100280
39,0,1.296000e+11,1.296000e+11,0.000101,76440049,64009.0,75898944.0,2005056,NaN,1,...,0.0,0.0,0.0,0,0,0,0,0,1,100306
40,0,6.125625e+10,6.125625e+10,0.000332,313608681,15288100.0,84529636.0,1600225,NaN,1,...,1.0,0.0,0.0,0,0,1,0,0,0,100311
41,0,2.148322e+11,2.148322e+11,0.000084,543495969,NaN,3261636.0,27112849,NaN,0,...,1.0,1.0,0.0,1,0,0,0,0,0,100312
42,0,2.906288e+11,2.025000e+11,0.000429,193210000,5253264.0,94864.0,32228329,441.0,1,...,0.0,0.0,0.0,0,0,1,0,0,0,100330
43,0,6.275206e+11,3.969000e+11,0.000072,319837456,6937956.0,51509329.0,1117249,169.0,1,...,0.0,0.0,0.0,0,0,1,0,0,0,100331
44,0,5.325964e+11,3.969000e+11,0.000982,358269184,2418025.0,43758225.0,6036849,9.0,1,...,0.0,1.0,0.0,0,0,1,0,0,0,100352
45,0,6.380447e+11,4.865062e+11,0.000325,344176704,5880625.0,10850436.0,4393216,NaN,1,...,1.0,0.0,0.0,0,0,0,0,0,1,100358
46,0,6.812100e+10,6.812100e+10,0.000211,393625600,14145121.0,1755625.0,11042329,196.0,1,...,0.0,1.0,0.0,0,0,1,0,0,0,100367
47,0,1.860024e+11,1.296000e+11,0.000053,137968516,3254416.0,1199025.0,8473921,484.0,1,...,0.0,0.0,0.0,0,0,0,0,0,1,100382
48,0,1.296000e+11,1.296000e+11,0.000332,143784081,1697809.0,27899524.0,876096,NaN,1,...,0.0,0.0,1.0,0,0,1,0,0,0,100384
49,0,2.964802e+11,2.964802e+11,0.000822,157929489,25411681.0,21529600.0,20839225,16.0,1,...,0.0,1.0,0.0,0,0,1,0,0,0,100385
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48694,0,2.678062e+11,2.678062e+11,0.000697,425720689,NaN,45792289.0,17572864,16.0,0,...,1.0,0.0,0.0,0,0,1,0,0,0,455805
48695,0,2.025000e+11,2.025000e+11,0.000697,476679889,NaN,86508601.0,22581504,NaN,0,...,0.0,0.0,1.0,0,0,1,0,0,0,455829
48696,0,6.625013e+10,5.688225e+10,0.000106,107661376,2917264.0,18232900.0,5793649,121.0,1,...,0.0,1.0,0.0,0,0,1,0,0,0,455840
48697,0,1.296000e+11,1.296000e+11,0.000136,215032896,8514724.0,8156736.0,4583881,NaN,1,...,0.0,0.0,0.0,0,0,0,0,0,1,455849
48698,0,5.062500e+10,5.062500e+10,0.000332,584092224,NaN,48427681.0,17648401,NaN,0,...,1.0,0.0,1.0,0,0,1,0,0,0,455850
48699,0,3.462911e+11,2.190240e+11,0.000120,84492864,1221025.0,77105961.0,3467044,NaN,1,...,0.0,0.0,1.0,0,0,1,0,0,0,455852
48700,0,2.065702e+11,2.065702e+11,0.000111,348680929,1934881.0,18139081.0,4915089,NaN,1,...,0.0,1.0,0.0,1,0,0,0,0,0,455854
48701,0,2.906288e+11,2.025000e+11,0.000606,444619396,NaN,85303696.0,8491396,NaN,0,...,1.0,0.0,0.0,0,0,1,0,0,0,455863
48702,0,5.618038e+10,3.240000e+10,0.000276,196897024,2601769.0,58293225.0,18062500,9.0,1,...,0.0,0.0,0.0,0,0,1,0,0,0,455897
48703,0,1.566307e+11,8.037225e+10,0.000982,489427129,NaN,49984900.0,18740241,NaN,0,...,1.0,0.0,0.0,0,0,1,0,0,0,455902
48704,0,1.822500e+10,1.822500e+10,0.000365,255840025,579121.0,8755681.0,25462116,NaN,1,...,1.0,1.0,0.0,0,0,1,0,0,0,455907
48705,0,4.556250e+11,4.556250e+11,0.000053,190191681,14424804.0,61246276.0,16032016,NaN,1,...,0.0,0.0,0.0,0,0,1,0,0,0,455908
48706,0,7.535025e+10,7.535025e+10,0.000232,280964644,129600.0,331776.0,91809,NaN,1,...,1.0,0.0,0.0,0,0,1,0,0,0,455909
48707,0,5.062500e+10,5.062500e+10,0.000100,103205281,399424.0,12299049.0,8076964,9.0,1,...,1.0,0.0,0.0,0,0,1,0,0,0,455940
48708,0,6.793321e+10,5.062500e+10,0.000101,135466321,2595321.0,9199089.0,18748900,NaN,1,...,0.0,0.0,0.0,1,0,0,0,0,0,455955
48709,0,1.029909e+11,8.037225e+10,0.000982,80102500,1990921.0,79637776.0,2673225,196.0,1,...,NaN,NaN,NaN,0,0,0,0,0,0,455958
48710,0,7.583029e+10,5.062500e+10,0.000053,135419769,20620681.0,26656569.0,14070001,169.0,1,...,0.0,0.0,0.0,0,0,0,0,0,1,455959
48711,0,1.265625e+12,1.265625e+12,0.000697,262602025,4879681.0,12439729.0,21911761,NaN,1,...,0.0,0.0,0.0,0,0,1,0,0,0,455960
48712,0,3.597336e+11,2.275290e+11,0.000065,227406400,1258884.0,229441.0,17106496,NaN,1,...,0.0,1.0,0.0,0,0,1,0,0,0,455961
48713,0,2.445596e+10,1.822500e+10,0.000113,142229476,8836.0,2374681.0,21224449,NaN,1,...,0.0,1.0,0.0,1,0,0,0,0,0,455962
48714,0,2.995066e+11,2.450250e+11,0.000429,143688169,3045025.0,42849.0,5688225,NaN,1,...,0.0,0.0,0.0,0,0,1,0,0,0,455963
48715,0,8.100000e+11,8.100000e+11,0.001281,299047849,23386896.0,60512841.0,693889,36.0,1,...,0.0,0.0,0.0,0,0,1,0,0,0,455965
48716,0,1.015346e+11,4.665600e+10,0.000068,158936449,5212089.0,42680089.0,17994564,NaN,1,...,0.0,0.0,0.0,0,0,1,0,0,0,456007
48717,0,3.240000e+10,3.240000e+10,0.000946,563207824,NaN,123099025.0,22372900,NaN,0,...,1.0,0.0,0.0,0,0,1,0,0,0,456008
48718,0,1.296000e+11,1.296000e+11,0.001281,202692169,24314761.0,145161.0,136161,NaN,1,...,1.0,1.0,0.0,0,0,1,0,0,0,456009
48719,0,4.765327e+11,3.014010e+11,0.000101,113784889,3916441.0,8838729.0,10989225,NaN,1,...,0.0,0.0,1.0,0,0,0,0,0,1,456010
48720,0,1.046264e+11,7.290000e+10,0.000606,168220900,93025.0,49294441.0,11881,144.0,1,...,0.0,1.0,1.0,0,0,0,0,0,1,456011
48721,0,2.193358e+11,1.463062e+11,0.001281,65318724,1713481.0,7756225.0,455625,NaN,1,...,0.0,0.0,0.0,0,0,1,0,0,0,456013
48722,0,2.772225e+10,2.772225e+10,0.000332,272448036,1716100.0,79637776.0,2209,NaN,1,...,1.0,1.0,0.0,0,0,0,0,0,1,456028
48723,0,9.922500e+10,9.922500e+10,0.000137,226532601,7946761.0,12117361.0,12117361,NaN,1,...,0.0,0.0,0.0,0,0,1,0,0,0,456058
48724,0,2.649264e+11,1.497690e+11,0.000410,251127409,4800481.0,26977636.0,17147881,NaN,1,...,0.0,0.0,0.0,0,0,0,0,0,1,456111
48725,0,2.025000e+11,2.025000e+11,0.000429,418775296,13890529.0,58798224.0,16104169,NaN,1,...,1.0,0.0,0.0,0,0,1,0,0,0,456114
48726,0,1.004683e+12,7.157160e+11,0.000040,279224100,4822416.0,79156609.0,64516,NaN,1,...,0.0,1.0,0.0,0,0,1,0,0,0,456115
48727,0,2.227735e+10,1.822500e+10,0.000325,252301456,42915601.0,2896804.0,19492225,NaN,1,...,0.0,1.0,0.0,0,0,1,0,0,0,456116
48728,0,4.697540e+11,3.422250e+11,0.000633,436726404,NaN,69039481.0,17960644,NaN,0,...,1.0,0.0,0.0,0,0,1,0,0,0,456119
48729,0,1.822500e+10,1.822500e+10,0.000068,173317225,2446096.0,32558436.0,5433561,NaN,1,...,0.0,0.0,0.0,0,0,0,0,0,1,456120
48730,0,1.981096e+11,1.640250e+11,0.000276,256608361,14130081.0,88078225.0,26214400,121.0,1,...,NaN,NaN,NaN,0,0,0,0,0,0,456122
48731,0,2.025000e+11,2.025000e+11,0.000232,421727296,NaN,90155025.0,15249025,196.0,0,...,0.0,1.0,1.0,0,0,1,0,0,0,456123
48732,0,2.301121e+11,2.025000e+11,0.000347,313856656,3594816.0,40678884.0,1540081,NaN,1,...,0.0,0.0,1.0,0,0,0,0,0,1,456166
48733,0,1.097824e+12,8.181202e+11,0.001281,400120009,13571856.0,93257649.0,12588304,NaN,1,...,0.0,1.0,0.0,0,0,1,0,0,0,456167
48734,0,6.983711e+11,5.852250e+11,0.000633,129663769,715716.0,87965641.0,6400900,NaN,1,...,0.0,0.0,0.0,0,0,1,0,0,0,456168
48735,0,1.188274e+10,8.100000e+09,0.000606,528770025,NaN,146119744.0,15904144,NaN,0,...,1.0,0.0,1.0,0,0,0,0,0,1,456169
48736,0,2.504902e+11,2.025000e+11,0.000045,474368400,NaN,115455025.0,27552001,144.0,0,...,0.0,0.0,0.0,0,0,1,0,0,0,456170
48737,0,1.296000e+11,1.296000e+11,0.000697,376243609,14161.0,19236996.0,8673025,NaN,1,...,1.0,1.0,0.0,0,0,1,0,0,0,456189
48738,0,6.351534e+10,4.733301e+10,0.000084,137077264,136161.0,30276.0,17455684,4225.0,1,...,0.0,1.0,1.0,0,0,1,0,0,0,456202
48739,0,1.702058e+11,7.290000e+10,0.000004,398800900,26718561.0,82700836.0,11553201,NaN,1,...,0.0,0.0,0.0,0,0,1,0,0,0,456221
48740,0,3.873979e+11,2.450250e+11,0.001281,125126596,1320201.0,9090225.0,9018009,NaN,1,...,0.0,1.0,0.0,0,0,0,0,0,1,456222
48741,0,9.922500e+10,9.922500e+10,0.000697,253510084,9223369.0,7187761.0,2262016,16.0,1,...,0.0,0.0,1.0,0,0,1,0,0,0,456223
48742,0,2.025000e+11,2.025000e+11,0.000355,195105024,7458361.0,2134521.0,1860496,NaN,1,...,0.0,0.0,1.0,0,0,0,0,0,1,456224
48743,0,9.782382e+10,7.290000e+10,0.000044,194937444,400689.0,1149184.0,17808400,484.0,1,...,1.0,0.0,0.0,0,0,1,0,0,0,456250

In [89]:
test_exaggerated.to_csv('test_exaggreated_data.csv', index=False) # deliberate spelling mistake to match train file