In [86]:
# numpy and pandas for data manipulation
import numpy as np
import pandas as pd 

# sklearn preprocessing for dealing with categorical variables
from sklearn.preprocessing import LabelEncoder

# File system manangement
import os


# matplotlib and seaborn for plotting
import matplotlib.pyplot as plt
import seaborn as sns 

windows_dir = "../kaggle/all/"
ubuntu_dir = "/home/prof/kaggle/unbankedcredit/kaggle/all/"

import platform

system = platform.system()

print("Notebook is running on operating system: {}".format(system))
if system == "Linux":
    directory = ubuntu_dir
else:
    directory = windows_dir

Notebook is running on operating system: Linux

In [87]:
def median_max(file):
    """function to return a dataframe of the median and max results in input csv file"""
    df = pd.read_csv(file, low_memory=True)
    print(df.info)
    df = df.apply(pd.to_numeric,errors="coerce", downcast="integer")
    df = df.apply(pd.to_numeric,errors="coerce", downcast="float")
    median = df.groupby('SK_ID_CURR').median()
    maximum = df.groupby('SK_ID_CURR').max()
    means_max = pd.merge(means, median, on="SK_ID_CURR", suffixes=("_MEDIAN","_MAX"))
    return means_max

In [88]:
bureau = median_max("/home/prof/kaggle/unbankedcredit/kaggle/all/bureau.csv")

<bound method DataFrame.info of          SK_ID_CURR  SK_ID_BUREAU CREDIT_ACTIVE CREDIT_CURRENCY  DAYS_CREDIT  \
0            215354       5714462        Closed      currency 1         -497
1            215354       5714463        Active      currency 1         -208
2            215354       5714464        Active      currency 1         -203
3            215354       5714465        Active      currency 1         -203
4            215354       5714466        Active      currency 1         -629
5            215354       5714467        Active      currency 1         -273
6            215354       5714468        Active      currency 1          -43
7            162297       5714469        Closed      currency 1        -1896
8            162297       5714470        Closed      currency 1        -1146
9            162297       5714471        Active      currency 1        -1146
10           162297       5714472        Active      currency 1        -1146
11           162297       5714473        Closed      currency 1        -2456
12           162297       5714474        Active      currency 1         -277
13           402440       5714475        Active      currency 1          -96
14           238881       5714482        Closed      currency 1         -318
15           238881       5714484        Closed      currency 1        -2911
16           238881       5714485        Closed      currency 1        -2148
17           238881       5714486        Active      currency 1         -381
18           238881       5714487        Active      currency 1          -95
19           238881       5714488        Closed      currency 1         -444
20           238881       5714489        Active      currency 1         -392
21           222183       5714491        Active      currency 1         -784
22           222183       5714492        Active      currency 1         -774
23           222183       5714493        Active      currency 1         -395
24           222183       5714495        Closed      currency 1        -2744
25           222183       5714496        Closed      currency 1        -1103
26           222183       5714497        Active      currency 1         -315
27           426155       5714498        Closed      currency 1        -1331
28           426155       5714499        Closed      currency 1        -2534
29           426155       5714500        Closed      currency 1         -845
...             ...           ...           ...             ...          ...
1716398      312021       5057541        Closed      currency 1        -1529
1716399      232638       5057553        Active      currency 1         -613
1716400      318662       5057561        Active      currency 1         -815
1716401      145715       5057569        Closed      currency 1        -2333
1716402      352358       5057580        Closed      currency 1        -1714
1716403      361928       5057589        Active      currency 1         -765
1716404      166279       5057599        Active      currency 1          -99
1716405      438109       5057605        Closed      currency 1        -2390
1716406      335468       5057618        Closed      currency 1        -2517
1716407      146896       5057629        Closed      currency 1        -1990
1716408      146896       5057632        Closed      currency 1         -434
1716409      146896       5057636        Closed      currency 1        -1705
1716410      280228       5057642        Active      currency 1         -575
1716411      232118       5057652        Closed      currency 1         -821
1716412      288038       5057657        Active      currency 1         -541
1716413      288038       5057665        Closed      currency 1         -463
1716414      445222       5057676        Closed      currency 1        -1628
1716415      317217       5057684        Closed      currency 1        -1970
1716416      433007       5057695        Closed      currency 1        -1100
1716417      433007       5057703        Active      currency 1         -740
1716418      433007       5057708        Closed      currency 1        -1389
1716419      352790       5057718        Closed      currency 1        -1808
1716420      352790       5057725        Closed      currency 1          -99
1716421      375755       5057734        Closed      currency 1        -1335
1716422      375755       5057742        Closed      currency 1        -2648
1716423      259355       5057750        Active      currency 1          -44
1716424      100044       5057754        Closed      currency 1        -2648
1716425      100044       5057762        Closed      currency 1        -1809
1716426      246829       5057770        Closed      currency 1        -1878
1716427      246829       5057778        Closed      currency 1         -463

         CREDIT_DAY_OVERDUE  DAYS_CREDIT_ENDDATE  DAYS_ENDDATE_FACT  \
0                         0               -153.0             -153.0
1                         0               1075.0                NaN
2                         0                528.0                NaN
3                         0                  NaN                NaN
4                         0               1197.0                NaN
5                         0              27460.0                NaN
6                         0                 79.0                NaN
7                         0              -1684.0            -1710.0
8                         0               -811.0             -840.0
9                         0               -484.0                NaN
10                        0               -180.0                NaN
11                        0               -629.0             -825.0
12                        0               5261.0                NaN
13                        0                269.0                NaN
14                        0               -187.0             -187.0
15                        0              -2607.0            -2604.0
16                        0              -1595.0             -987.0
17                        0                  NaN                NaN
18                        0               1720.0                NaN
19                        0                -77.0              -77.0
20                        0                  NaN                NaN
21                        0               1008.0                NaN
22                        0                625.0                NaN
23                        0               1431.0                NaN
24                        0              -2561.0            -2559.0
25                        0                 -7.0             -343.0
26                        0               1512.0                NaN
27                        0               -994.0            -1023.0
28                        0              -2352.0            -2347.0
29                        0               -480.0             -480.0
...                     ...                  ...                ...
1716398                   0               -829.0             -829.0
1716399                   0                721.0                NaN
1716400                   0               1011.0                NaN
1716401                   0              -2027.0            -1984.0
1716402                   0              -1530.0            -1564.0
1716403                   0               1061.0                NaN
1716404                   0                997.0                NaN
1716405                   0              -2053.0            -2082.0
1716406                   0               -660.0            -2363.0
1716407                   0              -1244.0            -1248.0
1716408                   0               -344.0             -344.0
1716409                   0               -582.0             -582.0
1716410                   0                813.0                NaN
1716411                   0               -425.0             -545.0
1716412                   0                  7.0                NaN
1716413                   0                -36.0              -36.0
1716414                   0              -1320.0            -1320.0
1716415                   0              -1577.0            -1577.0
1716416                   0               -732.0             -731.0
1716417                   0              31128.0                NaN
1716418                   0              -1299.0            -1299.0
1716419                   0              -1596.0            -1625.0
1716420                   0                -83.0              -98.0
1716421                   0              -1152.0            -1152.0
1716422                   0              31129.0             -189.0
1716423                   0                -30.0                NaN
1716424                   0              -2433.0            -2493.0
1716425                   0              -1628.0             -970.0
1716426                   0              -1513.0            -1513.0
1716427                   0                  NaN             -387.0

         AMT_CREDIT_MAX_OVERDUE  CNT_CREDIT_PROLONG  AMT_CREDIT_SUM  \
0                           NaN                   0       91323.000
1                           NaN                   0      225000.000
2                           NaN                   0      464323.500
3                           NaN                   0       90000.000
4                     77674.500                   0     2700000.000
5                         0.000                   0      180000.000
6                         0.000                   0       42103.800
7                     14985.000                   0       76878.450
8                         0.000                   0      103007.700
9                         0.000                   0        4500.000
10                        0.000                   0      337500.000
11                          NaN                   0      675000.000
12                        0.000                   0     7033500.000
13                        0.000                   0       89910.000
14                          NaN                   0           0.000
15                          NaN                   0       48555.000
16                          NaN                   0      135000.000
17                          NaN                   0      450000.000
18                          NaN                   0       67500.000
19                        0.000                   0      107184.060
20                        0.000                   0      252000.000
21                        0.000                   0           0.000
22                          NaN                   0      127840.500
23                          NaN                   0     1350000.000
24                      310.500                   0       18157.500
25                    20493.270                   0      675000.000
26                    88821.000                   0     3709552.500
27                     1350.000                   0       39433.500
28                          NaN                   0       38830.500
29                        0.000                   0       67500.000
...                         ...                 ...             ...
1716398                     NaN                   0      209898.000
1716399                     NaN                   0      972000.000
1716400                     NaN                   0      147150.000
1716401                 173.070                   0       35032.500
1716402                     NaN                   0       35271.000
1716403                     NaN                   0     1431000.000
1716404                   0.000                   0      450000.000
1716405               11317.590                   0      112204.350
1716406                   0.000                   0      473940.000
1716407                     NaN                   0       90000.000
1716408                     NaN                   0      234000.000
1716409                   0.000                   0           0.000
1716410                     NaN                   0       67500.000
1716411                   0.000                   0      108765.720
1716412                     NaN                   0      225000.000
1716413                6863.715                   0      110878.470
1716414                5693.625                   0       57834.000
1716415                     NaN                   0       93955.500
1716416                     NaN                   0       98775.000
1716417                     NaN                   0       67500.000
1716418                   0.000                   0      334158.435
1716419                8100.000                   0       28248.840
1716420                     NaN                   0       27000.000
1716421                     NaN                   0      195408.000
1716422                     NaN                   0      202500.000
1716423                   0.000                   0       11250.000
1716424                5476.500                   0       38130.840
1716425                     NaN                   0       15570.000
1716426                     NaN                   0       36000.000
1716427                     NaN                   0       22500.000

         AMT_CREDIT_SUM_DEBT  AMT_CREDIT_SUM_LIMIT  AMT_CREDIT_SUM_OVERDUE  \
0                      0.000                   NaN                     0.0
1                 171342.000                   NaN                     0.0
2                        NaN                   NaN                     0.0
3                        NaN                   NaN                     0.0
4                        NaN                   NaN                     0.0
5                  71017.380            108982.620                     0.0
6                  42103.800                 0.000                     0.0
7                      0.000                 0.000                     0.0
8                      0.000                 0.000                     0.0
9                      0.000                 0.000                     0.0
10                     0.000                 0.000                     0.0
11                     0.000                 0.000                     0.0
12                       NaN                   NaN                     0.0
13                 76905.000                 0.000                     0.0
14                     0.000                 0.000                     0.0
15                       NaN                   NaN                     0.0
16                       NaN                   NaN                     0.0
17                520920.000                   NaN                     0.0
18                  8131.500                   NaN                     0.0
19                     0.000                 0.000                     0.0
20                 23679.000            228320.100                     0.0
21                  -411.615               411.615                     0.0
22                     0.000                 0.000                     0.0
23               1185493.500                 0.000                     0.0
24                       NaN                   NaN                     0.0
25                     0.000                 0.000                     0.0
26                       NaN                   NaN                     0.0
27                     0.000                 0.000                     0.0
28                     0.000                 0.000                     0.0
29                     0.000                 0.000                     0.0
...                      ...                   ...                     ...
1716398                0.000                   NaN                     0.0
1716399           886297.500                 0.000                     0.0
1716400           105358.500                 0.000                     0.0
1716401                0.000                 0.000                     0.0
1716402                0.000                 0.000                     0.0
1716403          1092226.500                 0.000                     0.0
1716404           432787.500                 0.000                     0.0
1716405                0.000                 0.000                     0.0
1716406                0.000                 0.000                     0.0
1716407                  NaN                   NaN                     0.0
1716408                0.000                   NaN                     0.0
1716409                0.000                 0.000                     0.0
1716410                0.000                 0.000                     0.0
1716411                0.000                 0.000                     0.0
1716412            10971.000                 0.000                     0.0
1716413                0.000                 0.000                     0.0
1716414                0.000                 0.000                     0.0
1716415                  NaN                   NaN                     0.0
1716416                0.000                 0.000                     0.0
1716417             2466.000                   NaN                     0.0
1716418                0.000                 0.000                     0.0
1716419                0.000                 0.000                     0.0
1716420                0.000                 0.000                     0.0
1716421                0.000                   NaN                     0.0
1716422                0.000                   NaN                     0.0
1716423            11250.000                 0.000                     0.0
1716424                0.000                 0.000                     0.0
1716425                  NaN                   NaN                     0.0
1716426                0.000                 0.000                     0.0
1716427                0.000                   NaN                     0.0

             CREDIT_TYPE  DAYS_CREDIT_UPDATE  AMT_ANNUITY
0        Consumer credit                -131          NaN
1            Credit card                 -20          NaN
2        Consumer credit                 -16          NaN
3            Credit card                 -16          NaN
4        Consumer credit                 -21          NaN
5            Credit card                 -31          NaN
6        Consumer credit                 -22          NaN
7        Consumer credit               -1710          NaN
8        Consumer credit                -840          NaN
9            Credit card                -690          NaN
10           Credit card                -690          NaN
11       Consumer credit                -706          NaN
12              Mortgage                 -31          NaN
13       Consumer credit                 -22          NaN
14           Credit card                -185          NaN
15       Consumer credit               -2601          NaN
16       Consumer credit                -984          NaN
17       Consumer credit                  -4          NaN
18           Credit card                  -7          NaN
19       Consumer credit                 -71          NaN
20           Credit card                 -22          NaN
21           Credit card                -694          NaN
22           Credit card                -210          NaN
23       Consumer credit                 -24          NaN
24       Consumer credit               -2559          NaN
25       Consumer credit                -343          NaN
26              Car loan                 -32          NaN
27       Consumer credit               -1023          NaN
28       Consumer credit               -2345          NaN
29       Consumer credit                -480          NaN
...                  ...                 ...          ...
1716398  Consumer credit                -824          NaN
1716399      Credit card                 -42          NaN
1716400  Consumer credit                 -70          NaN
1716401  Consumer credit               -1984          NaN

In [89]:
# bureau_balance = median_max("/home/prof/kaggle/unbankedcredit/kaggle/all/bureau_balance.csv") # ID is bureau ID

In [90]:
credit_card_balance = median_max("/home/prof/kaggle/unbankedcredit/kaggle/all/credit_card_balance.csv")

<bound method DataFrame.info of          SK_ID_PREV  SK_ID_CURR  MONTHS_BALANCE  AMT_BALANCE  \
0           2562384      378907              -6       56.970
1           2582071      363914              -1    63975.555
2           1740877      371185              -7    31815.225
3           1389973      337855              -4   236572.110
4           1891521      126868              -1   453919.455
5           2646502      380010              -7    82903.815
6           1079071      171320              -6   353451.645
7           2095912      118650              -7    47962.125
8           2181852      367360              -4   291543.075
9           1235299      203885              -5   201261.195
10          1108284      209660              -7   102076.560
11          2740914      340339              -1   131669.145
12          1985699      302517              -4     1427.265
13          1441883      171537              -5        0.000
14          1864742      303581              -1        0.000
15          2037377      289902              -1   131294.340
16          1816636      255981              -6    72899.955
17          1039039      276642              -6        0.000
18          2016842      302450              -3        0.000
19          1189095      231608              -4   452774.700
20          1104090      259807              -6    45413.730
21          1683604      217113              -1    68710.140
22          2392920      132481              -1    85792.095
23          2021411      105755              -5   464452.470
24          1927949      323730              -3   152801.550
25          1885349      195164              -6   134249.445
26          2024137      184131              -3    67609.125
27          2272688      387286              -6    76235.940
28          2561523      213409              -2   137812.185
29          1288249      406607              -4        0.000
...             ...         ...             ...          ...
3840282     2208658      330072              -8        0.000
3840283     1319733      402678              -7       13.950
3840284     2464872      383896              -8        0.000
3840285     2622308      111891             -16        0.000
3840286     2711888      419785             -15        0.000
3840287     1050314      350128             -10   458892.135
3840288     1814640      309333             -15   458892.135
3840289     1914593      438678              -9        0.000
3840290     1948908      254265              -9        0.000
3840291     1925246      372892              -9   308056.005
3840292     1261707      130324              -9   270242.955
3840293     2353567      335296              -8        0.000
3840294     2102144      362478             -14        0.000
3840295     1920532      145486             -11   457382.340
3840296     1681780      433930             -11        0.000
3840297     2080215      105241             -11        0.000
3840298     1545164      193697             -10   260671.500
3840299     2029117      346347             -16    81697.275
3840300     1083973      438456              -8    81697.275
3840301     1409561      120617             -11   277204.095
3840302     2032117      355450             -11        0.000
3840303     1307188      385981              -9        0.000
3840304     1301378      303373             -15        0.000
3840305     2621524      172581             -11        0.000
3840306     1410474      255737             -13        0.000
3840307     1036507      328243              -9        0.000
3840308     1714892      347207              -9        0.000
3840309     1302323      215757              -9   275784.975
3840310     1624872      430337             -10        0.000
3840311     2411345      236760             -10        0.000

         AMT_CREDIT_LIMIT_ACTUAL  AMT_DRAWINGS_ATM_CURRENT  \
0                         135000                       0.0
1                          45000                    2250.0
2                         450000                       0.0
3                         225000                    2250.0
4                         450000                       0.0
5                         270000                       0.0
6                         585000                   67500.0
7                          45000                   45000.0
8                         292500                   90000.0
9                         225000                   76500.0
10                        180000                   92250.0
11                        225000                   10800.0
12                        135000                    4500.0
13                        270000                       0.0
14                         45000                       0.0
15                        135000                       0.0
16                        450000                   67500.0
17                         67500                       0.0
18                             0                       0.0
19                        450000                    9000.0
20                         45000                  105750.0
21                         67500                       0.0
22                        135000                   45000.0
23                        450000                  135000.0
24                        157500                       0.0
25                        157500                       0.0
26                        450000                   42750.0
27                        180000                   31500.0
28                        180000                       0.0
29                        270000                       0.0
...                          ...                       ...
3840282                        0                       0.0
3840283                   765000                       0.0
3840284                        0                       0.0
3840285                        0                       0.0
3840286                        0                       0.0
3840287                   450000                   31500.0
3840288                   450000                   31500.0
3840289                    45000                       0.0
3840290                        0                       0.0
3840291                   405000                       0.0
3840292                   292500                   18000.0
3840293                        0                       0.0
3840294                        0                       0.0
3840295                   900000                  180000.0
3840296                        0                       0.0
3840297                   450000                       0.0
3840298                   270000                       0.0
3840299                   765000                   20250.0
3840300                   765000                   20250.0
3840301                   450000                    4500.0
3840302                    45000                       0.0
3840303                        0                       NaN
3840304                        0                       0.0
3840305                        0                       0.0
3840306                   180000                       NaN
3840307                    45000                       NaN
3840308                    45000                       0.0
3840309                   585000                  270000.0
3840310                   450000                       NaN
3840311                   157500                       0.0

         AMT_DRAWINGS_CURRENT  AMT_DRAWINGS_OTHER_CURRENT  \
0                     877.500                         0.0
1                    2250.000                         0.0
2                       0.000                         0.0
3                    2250.000                         0.0
4                   11547.000                         0.0
5                       0.000                         0.0
6                   67500.000                         0.0
7                   45000.000                         0.0
8                  289339.425                         0.0
9                  111026.700                         0.0
10                  92250.000                         0.0
11                  10800.000                         0.0
12                 101304.720                         0.0
13                      0.000                         0.0
14                      0.000                         0.0
15                      0.000                         0.0
16                  67500.000                         0.0
17                      0.000                         0.0
18                      0.000                         0.0
19                   9000.000                         0.0
20                 105750.000                         0.0
21                   4412.250                         0.0
22                  63337.815                         0.0
23                 279112.500                    137700.0
24                      0.000                         0.0
25                      0.000                         0.0
26                  76131.000                         0.0
27                  32985.000                         0.0
28                   3100.500                         0.0
29                      0.000                         0.0
...                       ...                         ...
3840282                 0.000                         0.0
3840283                 0.000                         0.0
3840284                 0.000                         0.0
3840285                 0.000                         0.0
3840286                 0.000                         0.0
3840287             31500.000                         0.0
3840288             31500.000                         0.0
3840289                 0.000                         0.0
3840290                 0.000                         0.0
3840291                 0.000                         0.0
3840292             18000.000                         0.0
3840293                 0.000                         0.0
3840294                 0.000                         0.0
3840295            180000.000                         0.0
3840296                 0.000                         0.0
3840297               697.500                         0.0
3840298                 0.000                         0.0
3840299             20250.000                         0.0
3840300             20250.000                         0.0
3840301              4500.000                         0.0
3840302                 0.000                         0.0
3840303                 0.000                         NaN
3840304                 0.000                         0.0
3840305                 0.000                         0.0
3840306                 0.000                         NaN
3840307                 0.000                         NaN
3840308                 0.000                         0.0
3840309            270000.000                         0.0
3840310                 0.000                         NaN
3840311                 0.000                         0.0

         AMT_DRAWINGS_POS_CURRENT  AMT_INST_MIN_REGULARITY     ...      \
0                         877.500                 1700.325     ...
1                           0.000                 2250.000     ...
2                           0.000                 2250.000     ...
3                           0.000                11795.760     ...
4                       11547.000                22924.890     ...
5                           0.000                 4449.105     ...
6                           0.000                14684.175     ...
7                           0.000                    0.000     ...
8                      199339.425                  130.500     ...
9                       34526.700                 6338.340     ...
10                          0.000                    0.000     ...
11                          0.000                 6000.480     ...
12                      96804.720                 3023.955     ...
13                          0.000                12218.490     ...
14                          0.000                    0.000     ...
15                          0.000                 6774.660     ...
16                          0.000                 2457.720     ...
17                          0.000                    0.000     ...
18                          0.000                    0.000     ...
19                          0.000                22916.475     ...
20                          0.000                 1471.005     ...
21                       4412.250                 3315.240     ...
22                      18337.815                 2250.000     ...
23                       6412.500                 8921.970     ...
24                          0.000                 7875.000     ...
25                          0.000                 6906.555     ...
26                      33381.000                 2250.000     ...
27                       1485.000                 2250.000     ...
28                       3100.500                 7041.645     ...
29                          0.000                    0.000     ...
...                           ...                      ...     ...
3840282                     0.000                    0.000     ...
3840283                     0.000                    0.000     ...
3840284                     0.000                    0.000     ...
3840285                     0.000                    0.000     ...
3840286                     0.000                    0.000     ...
3840287                     0.000                31500.000     ...
3840288                     0.000                31500.000     ...
3840289                     0.000                    0.000     ...
3840290                     0.000                    0.000     ...
3840291                     0.000                20580.885     ...
3840292                     0.000                13596.255     ...
3840293                     0.000                    0.000     ...
3840294                     0.000                    0.000     ...
3840295                     0.000                16258.320     ...
3840296                     0.000                    0.000     ...
3840297                   697.500                    0.000     ...
3840298                     0.000                13500.000     ...
3840299                     0.000                    0.000     ...
3840300                     0.000                    0.000     ...
3840301                     0.000                13537.980     ...
3840302                     0.000                    0.000     ...
3840303                       NaN                    0.000     ...
3840304                     0.000                    0.000     ...
3840305                     0.000                    0.000     ...
3840306                       NaN                    0.000     ...
3840307                       NaN                    0.000     ...
3840308                     0.000                    0.000     ...
3840309                     0.000                 2250.000     ...
3840310                       NaN                    0.000     ...
3840311                     0.000                    0.000     ...

         AMT_RECIVABLE  AMT_TOTAL_RECEIVABLE  CNT_DRAWINGS_ATM_CURRENT  \
0                0.000                 0.000                       0.0
1            64875.555             64875.555                       1.0
2            31460.085             31460.085                       0.0
3           233048.970            233048.970                       1.0
4           453919.455            453919.455                       0.0
5            82773.315             82773.315                       0.0
6           351881.145            351881.145                       1.0
7            47962.125             47962.125                       1.0
8           286831.575            286831.575                       3.0
9           197224.695            197224.695                       3.0
10           94224.060             94224.060                       5.0
11          127891.935            127891.935                       2.0
12               0.000                 0.000                       1.0
13               0.000                 0.000                       0.0
14               0.000                 0.000                       0.0
15          131294.340            131294.340                       0.0
16           71554.455             71554.455                       1.0
17               0.000                 0.000                       0.0
18               0.000                 0.000                       0.0
19          451429.200            451429.200                       1.0
20           44068.230             44068.230                       3.0
21           68710.140             68710.140                       0.0
22           85792.095             85792.095                       1.0
23          456379.470            456379.470                       5.0
24          152801.550            152801.550                       0.0
25          134249.445            134249.445                       0.0
26           66263.625             66263.625                       1.0
27           76235.940             76235.940                       2.0
28          137812.185            137812.185                       0.0
29               0.000                 0.000                       0.0
...                ...                   ...                       ...
3840282          0.000                 0.000                       0.0
3840283          0.000                 0.000                       0.0
3840284          0.000                 0.000                       0.0
3840285          0.000                 0.000                       0.0
3840286          0.000                 0.000                       0.0
3840287     456651.135            456651.135                       2.0
3840288     456651.135            456651.135                       2.0
3840289          0.000                 0.000                       0.0
3840290          0.000                 0.000                       0.0
3840291     305116.920            305116.920                       0.0
3840292     268897.455            268897.455                       1.0
3840293          0.000                 0.000                       0.0
3840294          0.000                 0.000                       0.0
3840295     453345.840            453345.840                       4.0
3840296          0.000                 0.000                       0.0
3840297          0.000                 0.000                       0.0
3840298     260671.500            260671.500                       0.0
3840299      81697.275             81697.275                       2.0
3840300      81697.275             81697.275                       2.0
3840301     277204.095            277204.095                       1.0
3840302          0.000                 0.000                       0.0
3840303          0.000                 0.000                       NaN
3840304          0.000                 0.000                       0.0
3840305          0.000                 0.000                       0.0
3840306          0.000                 0.000                       NaN
3840307          0.000                 0.000                       NaN
3840308          0.000                 0.000                       0.0
3840309     273093.975            273093.975                       2.0
3840310          0.000                 0.000                       NaN
3840311          0.000                 0.000                       0.0

         CNT_DRAWINGS_CURRENT  CNT_DRAWINGS_OTHER_CURRENT  \
0                           1                         0.0
1                           1                         0.0
2                           0                         0.0
3                           1                         0.0
4                           1                         0.0

In [91]:
payments = median_max("/home/prof/kaggle/unbankedcredit/kaggle/all/installments_payments.csv")

<bound method DataFrame.info of           SK_ID_PREV  SK_ID_CURR  NUM_INSTALMENT_VERSION  \
0            1054186      161674                     1.0
1            1330831      151639                     0.0
2            2085231      193053                     2.0
3            2452527      199697                     1.0
4            2714724      167756                     1.0
5            1137312      164489                     1.0
6            2234264      184693                     4.0
7            1818599      111420                     2.0
8            2723183      112102                     0.0
9            1413990      109741                     1.0
10           1782554      106597                     1.0
11           2558880      154793                     1.0
12           1570206      147645                     0.0
13           1723268      197273                     1.0
14           1594684      100193                     0.0
15           1456258      118323                     1.0
16           1053286      170192                     1.0
17           1410565      197687                     1.0
18           2391610      183431                     0.0
19           2329072      183463                     1.0
20           1354314      196570                     1.0
21           2260765      106012                     3.0
22           1995642      134723                     1.0
23           2631836      140337                     0.0
24           2702769      102122                     1.0
25           1770345      128334                     1.0
26           1818333      191655                     1.0
27           1991673      162903                     0.0
28           1184783      140804                     0.0
29           1181315      174565                     1.0
...              ...         ...                     ...
13605371     1860833      415656                     2.0
13605372     1860833      415656                     1.0
13605373     1829584      450349                     1.0
13605374     1659443      405841                     0.0
13605375     2497183      419772                     0.0
13605376     1421163      453693                     0.0
13605377     2596933      419968                     1.0
13605378     2181137      409380                     0.0
13605379     1062206      409297                     0.0
13605380     1421163      453693                     0.0
13605381     1263000      406628                     0.0
13605382     2263477      443619                     1.0
13605383     1499195      418486                     6.0
13605384     2454112      400586                     0.0
13605385     2239217      451572                     0.0
13605386     1847946      405063                     0.0
13605387     2630714      441748                     1.0
13605388     2831819      417123                     0.0
13605389     2186857      428057                     0.0
13605390     1829584      450349                     1.0
13605391     1499195      418486                     6.0
13605392     2448869      434321                     1.0
13605393     1285736      434069                     0.0
13605394     1659443      405841                     0.0
13605395     1499195      418486                     6.0
13605396     2186857      428057                     0.0
13605397     1310347      414406                     0.0
13605398     1308766      402199                     0.0
13605399     1062206      409297                     0.0
13605400     2448869      434321                     1.0

          NUM_INSTALMENT_NUMBER  DAYS_INSTALMENT  DAYS_ENTRY_PAYMENT  \
0                             6          -1180.0             -1187.0
1                            34          -2156.0             -2156.0
2                             1            -63.0               -63.0
3                             3          -2418.0             -2426.0
4                             2          -1383.0             -1366.0
5                            12          -1384.0             -1417.0
6                            11           -349.0              -352.0
7                             4           -968.0              -994.0
8                            14           -197.0              -197.0
9                             4           -570.0              -609.0
10                            3           -933.0              -937.0
11                            8          -1262.0             -1269.0
12                           20           -761.0              -761.0
13                           14           -755.0              -800.0
14                           56          -1153.0             -1153.0
15                            6          -2619.0             -2619.0
16                            7           -500.0              -503.0
17                            1          -1037.0             -1048.0
18                           20          -1680.0             -1693.0
19                           11          -1699.0             -1693.0
20                           14           -361.0              -365.0
21                           23            -56.0               -59.0
22                           38          -1277.0             -1282.0
23                          116           -322.0              -322.0
24                            1           -281.0              -286.0
25                            5           -240.0              -255.0
26                            6           -345.0              -356.0
27                           46          -2548.0             -2561.0
28                          106           -155.0              -155.0
29                            7          -1894.0             -1895.0
...                         ...              ...                 ...
13605371                      1           -180.0                 NaN
13605372                      1           -180.0                 NaN
13605373                     18            -10.0                 NaN
13605374                    101          -1919.0                 NaN
13605375                     39          -1877.0                 NaN
13605376                     60          -1387.0                 NaN
13605377                     15            -42.0                 NaN
13605378                    108           -422.0                 NaN
13605379                     44          -1955.0                 NaN
13605380                     59          -1417.0                 NaN
13605381                     45           -808.0                 NaN
13605382                      9            -61.0                 NaN
13605383                     22           -412.0                 NaN
13605384                     27          -1720.0                 NaN
13605385                     76           -131.0                 NaN
13605386                     40          -2057.0                 NaN
13605387                      4            -36.0                 NaN
13605388                      8            -15.0                 NaN
13605389                     69          -1532.0                 NaN
13605390                     16            -70.0                 NaN
13605391                     32           -112.0                 NaN
13605392                     16           -117.0                 NaN
13605393                     73           -853.0                 NaN
13605394                    102          -1888.0                 NaN
13605395                      2          -1012.0                 NaN
13605396                     66          -1624.0                 NaN
13605397                     47          -1539.0                 NaN
13605398                     43             -7.0                 NaN
13605399                     43          -1986.0                 NaN
13605400                     19            -27.0                 NaN

          AMT_INSTALMENT  AMT_PAYMENT
0               6948.360     6948.360
1               1716.525     1716.525
2              25425.000    25425.000
3              24350.130    24350.130
4               2165.040     2160.585
5               5970.375     5970.375
6              29432.295    29432.295
7              17862.165    17862.165
8                 70.740       70.740
9              14308.470    14308.470
10             34620.525    34620.525
11             15031.080    15031.080
12                21.510       21.510
13              6093.990     6093.990
14               301.860      301.860
15              4844.925     4844.925
16              6882.840     6882.840
17             12514.050    12510.450
18              7875.000     7875.000
19              7283.295     7283.295
20             15219.000    15219.000
21             13494.915    13494.915
22             12949.200    12949.200
23               560.880      560.880
24              5178.195     5178.195
25             10649.925    10649.925
26             16479.270    16479.270
27              5400.000     5400.000
28               503.460      503.460
29             16274.790    16274.790
...                  ...          ...
13605371      344249.955          NaN
13605372       24127.200          NaN
13605373       18730.350          NaN
13605374          67.500          NaN
13605375          67.500          NaN
13605376          67.500          NaN
13605377       51394.680          NaN
13605378         130.500          NaN
13605379          67.500          NaN
13605380          67.500          NaN
13605381          67.500          NaN
13605382        5152.095          NaN
13605383       48635.595          NaN
13605384          67.500          NaN
13605385          46.980          NaN
13605386           0.090          NaN
13605387       14707.125          NaN
13605388        4399.740          NaN
13605389          67.500          NaN
13605390       18730.350          NaN
13605391       48635.595          NaN
13605392       11504.250          NaN
13605393          67.500          NaN
13605394          67.500          NaN
13605395       48635.595          NaN
13605396          67.500          NaN
13605397          67.500          NaN
13605398       43737.435          NaN
13605399          67.500          NaN
13605400       11504.250          NaN

[13605401 rows x 8 columns]>

In [92]:
pos = median_max("/home/prof/kaggle/unbankedcredit/kaggle/all/POS_CASH_balance.csv")

<bound method DataFrame.info of           SK_ID_PREV  SK_ID_CURR  MONTHS_BALANCE  CNT_INSTALMENT  \
0            1803195      182943             -31            48.0
1            1715348      367990             -33            36.0
2            1784872      397406             -32            12.0
3            1903291      269225             -35            48.0
4            2341044      334279             -35            36.0
5            2207092      342166             -32            12.0
6            1110516      204376             -38            48.0
7            1387235      153211             -35            36.0
8            1220500      112740             -31            12.0
9            2371489      274851             -32            24.0
10           2328294      287361             -32            12.0
11           2023570      237959             -39            12.0
12           1258390      278261             -32            36.0
13           1627166      146161             -33            24.0
14           1711625      131467             -34            12.0
15           2374177      204722             -35            24.0
16           1716688      405549             -33            12.0
17           1846127      380050             -31            36.0
18           1911764      312551             -32            24.0
19           2645133      152810             -35            24.0
20           1381005      195362             -34            60.0
21           1366811      169489             -38            24.0
22           1260621      244684             -32            18.0
23           1445556      220181             -41            12.0
24           1420240      386836             -41            12.0
25           2631694      337149             -33            12.0
26           1059679      139637             -31            12.0
27           1865970      202091             -35            12.0
28           2683316      454237             -32            18.0
29           2759941      428330             -32            18.0
...              ...         ...             ...             ...
10001328     2256531      422685             -20             6.0
10001329     1540335      104779             -27             6.0
10001330     1717234      141565             -18            12.0
10001331     2476257      210494             -18             6.0
10001332     2700641      448867             -18             6.0
10001333     2715817      417692             -18             6.0
10001334     2149359      305835             -19            12.0
10001335     1074985      433445             -22            12.0
10001336     1214793      292180             -21            12.0
10001337     2305826      356195             -18            12.0
10001338     1013514      305218             -27            16.0
10001339     1609165      370184             -21            15.0
10001340     1413755      233660             -19            24.0
10001341     2275842      293579             -20             6.0
10001342     1641388      165586             -19            10.0
10001343     1816071      383432             -23             6.0
10001344     1086035      102784             -26            24.0
10001345     1773550      412155             -18             6.0
10001346     2210119      381218             -22            12.0
10001347     1522999      385297             -21            12.0
10001348     2234984      191559             -22             6.0
10001349     2340692      104125             -24             6.0
10001350     2593362      198894             -20            12.0
10001351     2639809      288279             -25             6.0
10001352     2700641      448867             -19             6.0
10001353     2448283      226558             -20             6.0
10001354     1717234      141565             -19            12.0
10001355     1283126      315695             -21            10.0
10001356     1082516      450255             -22            12.0
10001357     1259607      174278             -52            16.0

          CNT_INSTALMENT_FUTURE NAME_CONTRACT_STATUS  SK_DPD  SK_DPD_DEF
0                          45.0               Active       0           0
1                          35.0               Active       0           0
2                           9.0               Active       0           0
3                          42.0               Active       0           0
4                          35.0               Active       0           0
5                          12.0               Active       0           0
6                          43.0               Active       0           0
7                          36.0               Active       0           0
8                          12.0               Active       0           0
9                          16.0               Active       0           0
10                         12.0               Active       0           0
11                         12.0               Active       0           0
12                         36.0               Active       0           0
13                         24.0               Active       0           0
14                          5.0               Active       0           0
15                         15.0               Active       0           0
16                          1.0               Active       0           0
17                         28.0               Active       0           0
18                         16.0               Active       0           0
19                         23.0               Active       0           0
20                         56.0               Active       0           0
21                         24.0               Active       0           0
22                         12.0               Active       0           0
23                         12.0               Active       0           0
24                         11.0               Active       0           0
25                         11.0               Active       0           0
26                         12.0               Active       0           0
27                          7.0               Active       0           0
28                         15.0               Active       0           0
29                         18.0               Active       0           0
...                         ...                  ...     ...         ...
10001328                    0.0               Active       0           0
10001329                    0.0               Active       0           0
10001330                    0.0               Active     630           0
10001331                    0.0               Active       0           0
10001332                    0.0               Active     871           0
10001333                    0.0               Active     948           0
10001334                    0.0               Active     903           0
10001335                    0.0               Active       0           0
10001336                    0.0               Active     850           0
10001337                    0.0               Active     804           0
10001338                    0.0               Signed       0           0
10001339                    0.0               Signed       0           0
10001340                    0.0               Signed       0           0
10001341                    0.0               Signed       0           0
10001342                    0.0               Active    1063           0
10001343                    0.0               Signed       0           0
10001344                    0.0               Active     654           0
10001345                    0.0               Signed       0           0
10001346                    0.0               Active    1016           0
10001347                    0.0               Active       0           0
10001348                    0.0               Active     797           0
10001349                    0.0               Active     944           0
10001350                    0.0            Completed       0           0
10001351                    0.0               Active     925           0
10001352                    0.0               Active     843           0
10001353                    0.0               Active     843           0
10001354                    0.0               Active     602           0
10001355                    0.0               Active     609           0
10001356                    0.0               Active     614           0
10001357                    0.0            Completed       0           0

[10001358 rows x 8 columns]>

In [93]:
previous = median_max("/home/prof/kaggle/unbankedcredit/kaggle/all/previous_application.csv")

<bound method DataFrame.info of          SK_ID_PREV  SK_ID_CURR NAME_CONTRACT_TYPE  AMT_ANNUITY  \
0           2030495      271877     Consumer loans     1730.430
1           2802425      108129         Cash loans    25188.615
2           2523466      122040         Cash loans    15060.735
3           2819243      176158         Cash loans    47041.335
4           1784265      202054         Cash loans    31924.395
5           1383531      199383         Cash loans    23703.930
6           2315218      175704         Cash loans          NaN
7           1656711      296299         Cash loans          NaN
8           2367563      342292         Cash loans          NaN
9           2579447      334349         Cash loans          NaN
10          1715995      447712         Cash loans    11368.620
11          2257824      161140         Cash loans    13832.775
12          2330894      258628         Cash loans    12165.210
13          1397919      321676     Consumer loans     7654.860
14          2273188      270658     Consumer loans     9644.220
15          1232483      151612     Consumer loans    21307.455
16          2163253      154602     Consumer loans     4187.340
17          1285768      142748    Revolving loans     9000.000
18          2393109      396305         Cash loans    10181.700
19          1173070      199178         Cash loans     4666.500
20          1506815      166490         Cash loans    25454.025
21          1182516      267782         Cash loans    20361.600
22          1172842      302212         Cash loans          NaN
23          1172937      302212         Cash loans    39475.305
24          1555330      199353         Cash loans          NaN
25          1543131      275707         Cash loans    22619.520
26          2536650      338725         Cash loans    16708.320
27          1676258      433469         Cash loans    22242.825
28          2075578      418383     Consumer loans     7656.705
29          1583704      315664         Cash loans          NaN
...             ...         ...                ...          ...
1670184     1458393      279524         Cash loans    48458.025
1670185     2815037      422867         Cash loans    54411.570
1670186     1433968      272570         Cash loans          NaN
1670187     1971628      435554         Cash loans          NaN
1670188     1713281      247019         Cash loans    26446.500
1670189     2406354      377114         Cash loans    26240.715
1670190     2381880      175920         Cash loans          NaN
1670191     1755809      122569    Revolving loans     2250.000
1670192     2101747      339383    Revolving loans     3375.000
1670193     1120445      179433    Revolving loans          NaN
1670194     2101748      280792         Cash loans    10482.795
1670195     2561520      334654     Consumer loans    24851.025
1670196     1662123      398290     Consumer loans          NaN
1670197     1854636      184353     Consumer loans    15708.150
1670198     1540903      212968     Consumer loans     2088.495
1670199     1077969      242303     Consumer loans     8546.940
1670200     1024416      331038         Cash loans     7576.920
1670201     1028905      442706     Consumer loans     6127.065
1670202     2205099      157707     Consumer loans     4334.355
1670203     2844282      383898     Consumer loans          NaN
1670204     1407146      198989         Cash loans    36598.095
1670205     2815130      338803         Cash loans    14584.050
1670206     2459206      238591         Cash loans    19401.435
1670207     1662353      443544         Cash loans    12607.875
1670208     1556789      209732         Cash loans    22299.390
1670209     2300464      352015     Consumer loans    14704.290
1670210     2357031      334635     Consumer loans     6622.020
1670211     2659632      249544     Consumer loans    11520.855
1670212     2785582      400317         Cash loans    18821.520
1670213     2418762      261212         Cash loans    16431.300

         AMT_APPLICATION  AMT_CREDIT  AMT_DOWN_PAYMENT  AMT_GOODS_PRICE  \
0                17145.0     17145.0               0.0          17145.0
1               607500.0    679671.0               NaN         607500.0
2               112500.0    136444.5               NaN         112500.0
3               450000.0    470790.0               NaN         450000.0
4               337500.0    404055.0               NaN         337500.0
5               315000.0    340573.5               NaN         315000.0
6                    0.0         0.0               NaN              NaN
7                    0.0         0.0               NaN              NaN
8                    0.0         0.0               NaN              NaN
9                    0.0         0.0               NaN              NaN
10              270000.0    335754.0               NaN         270000.0
11              211500.0    246397.5               NaN         211500.0
12              148500.0    174361.5               NaN         148500.0
13               53779.5     57564.0               0.0          53779.5
14               26550.0     27252.0               0.0          26550.0
15              126490.5    119853.0           12649.5         126490.5
16               26955.0     27297.0            1350.0          26955.0
17              180000.0    180000.0               NaN         180000.0
18              180000.0    180000.0               NaN         180000.0
19               45000.0     49455.0               NaN          45000.0
20              450000.0    491580.0               NaN         450000.0
21              405000.0    451777.5               NaN         405000.0
22                   0.0         0.0               NaN              NaN
23             1129500.0   1277104.5               NaN        1129500.0
24                   0.0         0.0               NaN              NaN
25              229500.0    241920.0               NaN         229500.0
26              369000.0    369000.0               NaN         369000.0
27              247500.0    268083.0               0.0         247500.0
28               74610.0     65610.0            9000.0          74610.0
29                   0.0         0.0               NaN              NaN
...                  ...         ...               ...              ...
1670184        1575000.0   1762110.0               NaN        1575000.0
1670185         450000.0    531000.0               NaN         450000.0
1670186              0.0         0.0               NaN              NaN
1670187              0.0         0.0               NaN              NaN
1670188         900000.0    900000.0               NaN         900000.0
1670189         796500.0    954207.0               NaN         796500.0
1670190              0.0         0.0               NaN              NaN
1670191          45000.0     45000.0               NaN          45000.0
1670192              0.0     67500.0               NaN              NaN
1670193              0.0         0.0               NaN              NaN
1670194          90000.0    107604.0               NaN          90000.0
1670195         248535.0    223681.5           24853.5         248535.0
1670196          57910.5     57910.5               0.0          57910.5
1670197         153220.5    153220.5               0.0         153220.5
1670198          22869.0     20578.5            2290.5          22869.0
1670199          37926.0     40932.0               0.0          37926.0
1670200          99000.0    112068.0               0.0          99000.0
1670201          45450.0     54126.0            2295.0          45450.0
1670202          22207.5     23854.5               0.0          22207.5
1670203          14791.5     14791.5               0.0          14791.5
1670204         450000.0    570073.5               NaN         450000.0
1670205         135000.0    182956.5               NaN         135000.0
1670206         180000.0    243936.0               0.0         180000.0
1670207         112500.0    112500.0               0.0         112500.0
1670208         315000.0    436216.5               NaN         315000.0
1670209         267295.5    311400.0               0.0         267295.5
1670210          87750.0     64291.5           29250.0          87750.0
1670211         105237.0    102523.5           10525.5         105237.0
1670212         180000.0    191880.0               NaN         180000.0
1670213         360000.0    360000.0               NaN         360000.0

        WEEKDAY_APPR_PROCESS_START  HOUR_APPR_PROCESS_START  \
0                         SATURDAY                       15
1                         THURSDAY                       11
2                          TUESDAY                       11
3                           MONDAY                        7
4                         THURSDAY                        9
5                         SATURDAY                        8
6                          TUESDAY                       11
7                           MONDAY                        7
8                           MONDAY                       15
9                         SATURDAY                       15
10                          FRIDAY                        7
11                          FRIDAY                       10
12                         TUESDAY                       15
13                          SUNDAY                       15
14                        SATURDAY                       10
15                         TUESDAY                        7
16                        SATURDAY                       12
17                          FRIDAY                       13
18                        THURSDAY                       14
19                        SATURDAY                       16
20                          MONDAY                        6
21                        SATURDAY                        4
22                         TUESDAY                        9
23                        THURSDAY                        5
24                        SATURDAY                        6
25                        THURSDAY                        8
26                       WEDNESDAY                       13
27                        THURSDAY                       14
28                          MONDAY                       14
29                       WEDNESDAY                       15
...                            ...                      ...
1670184                  WEDNESDAY                       10
1670185                     FRIDAY                        3
1670186                   THURSDAY                       15
1670187                     MONDAY                       10
1670188                     MONDAY                       20
1670189                  WEDNESDAY                       14
1670190                     FRIDAY                       11
1670191                  WEDNESDAY                       12
1670192                     FRIDAY                       18
1670193                     SUNDAY                       13
1670194                     MONDAY                       14
1670195                     FRIDAY                       17
1670196                   SATURDAY                        9
1670197                   SATURDAY                       12
1670198                     SUNDAY                       16
1670199                   THURSDAY                       12
1670200                     FRIDAY                       14
1670201                     MONDAY                       10
1670202                   THURSDAY                       10
1670203                    TUESDAY                       13
1670204                   THURSDAY                       12
1670205                   SATURDAY                       10
1670206                    TUESDAY                       13
1670207                     MONDAY                       10
1670208                   THURSDAY                       17
1670209                  WEDNESDAY                       12
1670210                    TUESDAY                       15
1670211                     MONDAY                       12
1670212                  WEDNESDAY                        9
1670213                     SUNDAY                       10

                   ...             NAME_SELLER_INDUSTRY  CNT_PAYMENT  \
0                  ...                     Connectivity         12.0
1                  ...                              XNA         36.0
2                  ...                              XNA         12.0
3                  ...                              XNA         12.0
4                  ...                              XNA         24.0
5                  ...                              XNA         18.0
6                  ...                              XNA          NaN
7                  ...                              XNA          NaN
8                  ...                              XNA          NaN
9                  ...                              XNA          NaN
10                 ...                              XNA         54.0
11                 ...                              XNA         30.0
12                 ...                              XNA         24.0
13                 ...             Consumer electronics          8.0
14                 ...             Consumer electronics          3.0
15                 ...                         Industry          6.0
16                 ...             Consumer electronics          8.0
17                 ...                              XNA          0.0
18                 ...                              XNA         24.0
19                 ...                              XNA         18.0
20                 ...                              XNA         24.0
21                 ...                              XNA         30.0
22                 ...                              XNA          NaN
23                 ...                              XNA         54.0
24                 ...                              XNA          NaN
25                 ...                              XNA         12.0
26                 ...             Consumer electronics         48.0
27                 ...             Consumer electronics         18.0
28                 ...                     Connectivity         12.0
29                 ...                              XNA          NaN
...                ...                              ...          ...
1670184            ...                              XNA         60.0
1670185            ...                              XNA         12.0
1670186            ...                              XNA          NaN
1670187            ...                              XNA          NaN
1670188            ...                              XNA         60.0
1670189            ...                              XNA         60.0
1670190            ...                              XNA          NaN
1670191            ...             Consumer electronics          0.0
1670192            ...                              XNA          0.0
1670193            ...                              XNA          NaN
1670194            ...                              XNA         12.0
1670195            ...                        Furniture         10.0
1670196            ...                     Connectivity          NaN
1670197            ...                     Construction         12.0
1670198            ...                     Connectivity         12.0
1670199            ...                     Connectivity          6.0
1670200            ...             Consumer electronics         24.0
1670201            ...                        Furniture         12.0
1670202            ...                         Clothing          6.0
1670203            ...                     Connectivity          NaN
1670204            ...                              XNA         24.0
1670205            ...                              XNA         24.0
1670206            ...                              XNA         24.0
1670207            ...                              XNA         12.0
1670208            ...                              XNA         36.0
1670209            ...                        Furniture         30.0
1670210            ...                        Furniture         12.0
1670211            ...             Consumer electronics         10.0
1670212            ...                              XNA         12.0
1670213            ...                              XNA         48.0

         NAME_YIELD_GROUP             PRODUCT_COMBINATION  DAYS_FIRST_DRAWING  \
0                  middle        POS mobile with interest            365243.0
1              low_action                Cash X-Sell: low            365243.0
2                    high               Cash X-Sell: high            365243.0
3                  middle             Cash X-Sell: middle            365243.0
4                    high               Cash Street: high                 NaN
5              low_normal                Cash X-Sell: low            365243.0
6                     XNA                            Cash                 NaN
7                     XNA                            Cash                 NaN
8                     XNA                            Cash                 NaN
9                     XNA                            Cash                 NaN
10             low_normal                Cash X-Sell: low            365243.0
11                 middle             Cash X-Sell: middle            365243.0
12                   high               Cash X-Sell: high            365243.0
13             low_action  POS household without interest            365243.0
14                 middle     POS household with interest            365243.0
15             low_normal         POS other with interest            365243.0
16                   high     POS household with interest            365243.0
17                    XNA                     Card X-Sell              -277.0
18             low_normal                Cash X-Sell: low                 NaN
19                   high               Cash Street: high                 NaN
20             low_normal                Cash X-Sell: low                 NaN
21             low_normal                Cash X-Sell: low            365243.0
22                    XNA                            Cash                 NaN
23             low_normal                Cash X-Sell: low                 NaN
24                    XNA                            Cash                 NaN
25             low_normal                Cash X-Sell: low            365243.0
26                 middle             Cash X-Sell: middle            365243.0
27                   high               Cash X-Sell: high            365243.0
28             low_normal        POS mobile with interest            365243.0
29                    XNA                            Cash                 NaN
...                   ...                             ...                 ...
1670184        low_normal                Cash X-Sell: low                 NaN
1670185            middle             Cash Street: middle                 NaN
1670186               XNA                            Cash                 NaN
1670187               XNA                            Cash                 NaN
1670188        low_normal                Cash X-Sell: low                 NaN
1670189        low_normal                Cash Street: low                 NaN
1670190               XNA                            Cash                 NaN
1670191               XNA                     Card Street                 NaN
1670192               XNA                     Card X-Sell              -474.0
1670193               XNA                     Card Street                 NaN
1670194        low_normal                Cash X-Sell: low            365243.0
1670195        low_normal      POS industry with interest            365243.0
1670196               XNA        POS mobile with interest                 NaN

In [94]:
def merger(df1, df2):
    df = pd.merge(df1,df2,on="SK_ID_CURR", how="left")
    return df

In [95]:
m1 = merger(bureau,credit_card_balance )
m1plus = merger(m1,payments)
m1plus2 = merger(m1plus,pos)
final = merger(m1plus2, previous)

In [96]:
final.head()

,SK_ID_BUREAU_MEDIAN,CREDIT_ACTIVE_MEDIAN,CREDIT_CURRENCY_MEDIAN,DAYS_CREDIT_MEDIAN,CREDIT_DAY_OVERDUE_MEDIAN,DAYS_CREDIT_ENDDATE_MEDIAN,DAYS_ENDDATE_FACT_MEDIAN,AMT_CREDIT_MAX_OVERDUE_MEDIAN,CNT_CREDIT_PROLONG_MEDIAN,AMT_CREDIT_SUM_MEDIAN,...,NAME_SELLER_INDUSTRY,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
SK_ID_CURR,,,,,,,,,,,,,,,,,,,,,
100001.0,5896633.0,NaN,NaN,-857.0,0.0,-179.0,-715.0,NaN,0.0,168345.000000,...,NaN,8.0,NaN,NaN,365243.0,-1709.0,-1499.0,-1619.0,-1612.0,0.0
100002.0,6158905.5,NaN,NaN,-1042.5,0.0,-424.5,-939.0,40.5,0.0,54130.500000,...,NaN,24.0,NaN,NaN,365243.0,-565.0,125.0,-25.0,-17.0,0.0
100003.0,5885878.5,NaN,NaN,-1205.5,0.0,-480.0,-621.0,0.0,0.0,92576.250000,...,NaN,12.0,NaN,NaN,365243.0,-797.0,-647.0,-647.0,-639.0,1.0
100004.0,6829133.5,NaN,NaN,-867.0,0.0,-488.5,-532.5,0.0,0.0,94518.898438,...,NaN,4.0,NaN,NaN,365243.0,-784.0,-694.0,-724.0,-714.0,0.0
100005.0,6735201.0,NaN,NaN,-137.0,0.0,122.0,-123.0,0.0,0.0,58500.000000,...,NaN,12.0,NaN,NaN,365243.0,-706.0,-376.0,-466.0,-460.0,0.0

Drop columns with only NaN

In [97]:
final.dropna(axis=1, how='all', inplace=True)

In [98]:
final.info()

<class 'pandas.core.frame.DataFrame'>
Float64Index: 305811 entries, 100001.0 to 456255.0
Columns: 132 entries, SK_ID_BUREAU_MEDIAN to NFLAG_INSURED_ON_APPROVAL
dtypes: float32(101), float64(31)
memory usage: 192.5 MB

In [99]:
final_median = final.filter(regex="MEDIAN")

In [100]:
final_max = final.filter(regex="MAX")

In [101]:
combined = pd.merge(final_median, final_max, on="SK_ID_CURR")

In [102]:
combined.head()

,SK_ID_BUREAU_MEDIAN,DAYS_CREDIT_MEDIAN,CREDIT_DAY_OVERDUE_MEDIAN,DAYS_CREDIT_ENDDATE_MEDIAN,DAYS_ENDDATE_FACT_MEDIAN,AMT_CREDIT_MAX_OVERDUE_MEDIAN_x,CNT_CREDIT_PROLONG_MEDIAN,AMT_CREDIT_SUM_MEDIAN,AMT_CREDIT_SUM_DEBT_MEDIAN,AMT_CREDIT_SUM_LIMIT_MEDIAN,...,AMT_CREDIT_SUM_DEBT_MAX,AMT_CREDIT_SUM_LIMIT_MAX,AMT_CREDIT_SUM_OVERDUE_MAX,DAYS_CREDIT_UPDATE_MAX,AMT_ANNUITY_MAX_x,AMT_CREDIT_MAX_OVERDUE_x,AMT_CREDIT_MAX_OVERDUE_y,AMT_CREDIT_MAX_OVERDUE_x,AMT_CREDIT_MAX_OVERDUE_y,AMT_ANNUITY_MAX_y
SK_ID_CURR,,,,,,,,,,,,,,,,,,,,,
100001.0,5896633.0,-857.0,0.0,-179.0,-715.0,NaN,0.0,168345.000000,0.0,0.0,...,0.0,0.0,0.0,-155.0,0.0,NaN,NaN,NaN,NaN,3951.000000
100002.0,6158905.5,-1042.5,0.0,-424.5,-939.0,40.5,0.0,54130.500000,0.0,0.0,...,0.0,0.0,0.0,-402.5,0.0,NaN,40.5,40.5,40.5,9251.775391
100003.0,5885878.5,-1205.5,0.0,-480.0,-621.0,0.0,0.0,92576.250000,0.0,0.0,...,0.0,0.0,0.0,-545.0,NaN,NaN,0.0,0.0,0.0,64567.664062
100004.0,6829133.5,-867.0,0.0,-488.5,-532.5,0.0,0.0,94518.898438,0.0,0.0,...,0.0,0.0,0.0,-532.0,NaN,NaN,0.0,0.0,0.0,5357.250000
100005.0,6735201.0,-137.0,0.0,122.0,-123.0,0.0,0.0,58500.000000,25321.5,0.0,...,25321.5,0.0,0.0,-31.0,0.0,NaN,0.0,0.0,0.0,4813.200195

In [103]:
combined.drop(columns='SK_ID_BUREAU_MEDIAN', inplace=True) # dropping bureau ID

In [104]:
combined.drop(columns='SK_ID_BUREAU_MAX', inplace=True) # dropping bureau ID

In [105]:
combined.head()

,DAYS_CREDIT_MEDIAN,CREDIT_DAY_OVERDUE_MEDIAN,DAYS_CREDIT_ENDDATE_MEDIAN,DAYS_ENDDATE_FACT_MEDIAN,AMT_CREDIT_MAX_OVERDUE_MEDIAN_x,CNT_CREDIT_PROLONG_MEDIAN,AMT_CREDIT_SUM_MEDIAN,AMT_CREDIT_SUM_DEBT_MEDIAN,AMT_CREDIT_SUM_LIMIT_MEDIAN,AMT_CREDIT_SUM_OVERDUE_MEDIAN,...,AMT_CREDIT_SUM_DEBT_MAX,AMT_CREDIT_SUM_LIMIT_MAX,AMT_CREDIT_SUM_OVERDUE_MAX,DAYS_CREDIT_UPDATE_MAX,AMT_ANNUITY_MAX_x,AMT_CREDIT_MAX_OVERDUE_x,AMT_CREDIT_MAX_OVERDUE_y,AMT_CREDIT_MAX_OVERDUE_x,AMT_CREDIT_MAX_OVERDUE_y,AMT_ANNUITY_MAX_y
SK_ID_CURR,,,,,,,,,,,,,,,,,,,,,
100001.0,-857.0,0.0,-179.0,-715.0,NaN,0.0,168345.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,-155.0,0.0,NaN,NaN,NaN,NaN,3951.000000
100002.0,-1042.5,0.0,-424.5,-939.0,40.5,0.0,54130.500000,0.0,0.0,0.0,...,0.0,0.0,0.0,-402.5,0.0,NaN,40.5,40.5,40.5,9251.775391
100003.0,-1205.5,0.0,-480.0,-621.0,0.0,0.0,92576.250000,0.0,0.0,0.0,...,0.0,0.0,0.0,-545.0,NaN,NaN,0.0,0.0,0.0,64567.664062
100004.0,-867.0,0.0,-488.5,-532.5,0.0,0.0,94518.898438,0.0,0.0,0.0,...,0.0,0.0,0.0,-532.0,NaN,NaN,0.0,0.0,0.0,5357.250000
100005.0,-137.0,0.0,122.0,-123.0,0.0,0.0,58500.000000,25321.5,0.0,0.0,...,25321.5,0.0,0.0,-31.0,0.0,NaN,0.0,0.0,0.0,4813.200195

In [106]:
# # train enhanced
train_file = "/home/prof/kaggle/unbankedcredit/train_enhanced_loan_history_cc_pos_previous.csv"
train = pd.read_csv(train_file, low_memory=True)
# train_non_na = train.fillna(0).astype(int)
# train_non_na.astype('int64','int32')
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307511 entries, 0 to 307510
Columns: 961 entries, SK_ID_CURR to PREVIOUS_COUNT
dtypes: bool(1), float64(786), int64(173), object(1)
memory usage: 2.2+ GB

In [107]:
train = train.apply(pd.to_numeric,errors="coerce", downcast="integer")
train = train.apply(pd.to_numeric,errors="coerce", downcast="float")

In [108]:
train_final = pd.merge(train,combined,on="SK_ID_CURR", how="left")

In [109]:
train_final.to_csv('train_all.csv')

In [110]:
# # test enhanced
test_file = "/home/prof/kaggle/unbankedcredit/test_enhanced_loan_history_cc_pos_previous.csv"
test = pd.read_csv(test_file, low_memory=True)
# train_non_na = train.fillna(0).astype(int)
# train_non_na.astype('int64','int32')
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48744 entries, 0 to 48743
Columns: 960 entries, SK_ID_CURR to PREVIOUS_COUNT
dtypes: bool(1), float64(786), int64(172), object(1)
memory usage: 356.7+ MB

In [111]:
test = test.apply(pd.to_numeric,errors="coerce", downcast="integer")
test = test.apply(pd.to_numeric,errors="coerce", downcast="float")

In [112]:
test_final = pd.merge(test,combined,on="SK_ID_CURR", how="left")

In [113]:
test_final.to_csv('test_all.csv')