In [1]:
import sys
# numpy and pandas for data manipulation
import numpy as np
import pandas as pd 

# sklearn preprocessing for dealing with categorical variables
from sklearn.preprocessing import LabelEncoder

# File system manangement
import os


# matplotlib and seaborn for plotting
import matplotlib.pyplot as plt
import seaborn as sns 

windows_dir = "../kaggle/all/"
ubuntu_dir = "/home/prof/kaggle/unbankedcredit/kaggle/all/"

import platform

system = platform.system()

print("Notebook is running on operating system: {}".format(system))
if system == "Linux":
    directory = ubuntu_dir
else:
    directory = windows_dir

Notebook is running on operating system: Linux

In [2]:
# # Installments 
types_dict = {'SK_ID_PREV': 'int32',
              'SK_ID_CURR': 'int32',
              'NUM_INSTALMENT_VERSION': 'float32',
              'NUM_INSTALMENT_NUMBER': 'int32',
              'DAYS_INSTALMENT': 'float32',
              'DAYS_ENTRY_PAYMENT': 'float32',
              'AMT_INSTALMENT': 'float32',
              'AMT_PAYMENT': 'float32',
              'DAYS_IN_ADVANCE': 'float32',
              'AMT_UNDERPAYMENT': 'float32'
           
    
    
}
install_file = "/home/prof/kaggle/unbankedcredit/installments_payments_enhanced.csv"
installments = pd.read_csv(install_file, low_memory=True, dtype=types_dict)

In [3]:
# # train enhanced
# train_file = "/home/prof/kaggle/unbankedcredit/train_enhanced_bur.csv"
# train = pd.read_csv(train_file, low_memory=True)
# train_non_na = train.fillna(0).astype(int)
# train_non_na.astype('int64','int32')

In [4]:
# train_enhanced_loan_history = pd.merge(train_non_na,installments, on='SK_ID_CURR', how='left')

In [5]:
# train_enhanced_loan_history.to_csv('train_enhanced_loan_history.csv', index=False)

In [6]:
# train enhanced
test_file = "/home/prof/kaggle/unbankedcredit/test_enhanced_bur.csv"
test = pd.read_csv(test_file, low_memory=True)
test_non_na = test.fillna(0).astype(int)
test_non_na.astype('int64','int32')

,SK_ID_CURR,NAME_CONTRACT_TYPE,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,...,DAYS_CREDIT_ENDDATE_mean,DAYS_ENDDATE_FACT_mean,AMT_CREDIT_MAX_OVERDUE_mean,CNT_CREDIT_PROLONG_mean,AMT_CREDIT_SUM_mean,AMT_CREDIT_SUM_DEBT_mean,AMT_CREDIT_SUM_LIMIT_mean,AMT_CREDIT_SUM_OVERDUE_mean,DAYS_CREDIT_UPDATE_mean,AMT_ANNUITY_mean
0,100001,0,0,1,0,135000,568800,20560,450000,0,...,82,-825,0,0,207623,85240,0,0,-93,3545
1,100005,0,0,1,0,99000,222768,17370,180000,0,...,439,-123,0,0,219042,189469,0,0,-54,1420
2,100013,0,1,1,0,202500,663264,69777,630000,0,...,-1068,-1054,19305,0,518070,0,0,0,-775,0
3,100028,0,0,1,2,315000,1575000,49018,1575000,0,...,2387,-1238,0,0,126739,18630,14484,0,-651,3012
4,100038,0,1,0,1,180000,625500,32067,625500,0,...,0,0,0,0,0,0,0,0,0,0
5,100042,0,1,1,0,270000,959688,34600,810000,0,...,620,-1241,1312,0,681475,256180,0,0,-541,17038
6,100057,0,1,1,2,180000,499221,22117,373500,0,...,99,-977,0,0,369032,0,0,0,-887,2367
7,100065,0,0,1,0,166500,180000,14220,180000,0,...,1749,-565,0,0,131605,60030,1487,0,-436,4901
8,100066,0,0,1,0,315000,364896,28957,315000,0,...,1129,-315,0,0,316500,60562,0,0,-233,0
9,100067,0,1,1,1,162000,45000,5337,45000,0,...,2872,-325,0,0,190417,84069,1991,0,-263,6745
10,100074,0,0,1,0,67500,675000,25447,675000,0,...,-1022,-1023,2005,0,120324,0,0,0,-1021,0
11,100090,0,0,1,0,135000,261621,16848,216000,0,...,103,0,0,0,56520,31085,0,0,-15,0
12,100091,0,0,1,0,247500,296280,23539,225000,0,...,465,-398,0,0,649948,455887,0,0,-12,0
13,100092,0,1,1,0,90000,360000,18535,360000,0,...,-205,-1015,5849,0,170352,78109,0,0,-558,5580
14,100106,1,0,1,0,180000,157500,7875,157500,0,...,0,-809,0,0,225000,0,0,0,-809,0
15,100107,0,1,1,0,180000,296280,21690,225000,0,...,349,0,0,0,124195,124195,0,0,-17,10031
16,100109,0,1,1,0,202500,407520,26041,360000,0,...,1690,-1252,11835,0,128473,24548,0,0,-649,4582
17,100117,0,1,1,0,90000,499221,22117,373500,0,...,-360,-974,0,0,223032,96005,56736,0,-683,8053
18,100128,0,1,1,1,225000,431280,23526,360000,0,...,4150,-1022,570,0,282561,34760,16177,0,-953,4718
19,100141,0,1,1,0,175500,478498,46741,454500,0,...,0,0,0,0,0,0,0,0,0,0
20,100150,0,0,1,0,99000,225000,19242,225000,0,...,-1846,-1945,1906,0,106875,0,0,0,-733,0
21,100168,0,0,1,0,157500,266652,16443,202500,0,...,-676,-781,0,0,360000,0,0,0,-779,0
22,100169,0,0,1,0,135000,540000,27702,540000,0,...,118,0,7,0,176382,97011,0,0,-36,16033
23,100170,0,0,1,1,337500,1313212,42493,1012500,0,...,11512,-557,0,0,68277,39458,5992,0,-267,6358
24,100171,0,1,1,0,157500,539100,29245,450000,0,...,57,-1399,7435,0,779664,331079,0,0,-899,16929
25,100172,0,0,1,0,76500,225000,12334,225000,0,...,303,-179,0,0,106012,19347,0,0,-113,2238
26,100184,0,0,1,0,112500,256032,10759,180000,0,...,16,-419,0,0,129297,79060,0,0,-247,4996
27,100187,0,0,1,0,225000,501363,25726,418500,0,...,194,-450,0,0,1103223,468950,0,0,-343,33750
28,100212,0,1,0,0,90000,450000,23107,450000,0,...,107,0,0,0,23502,16299,0,0,-16,3357
29,100222,0,1,1,0,360000,945000,34074,945000,0,...,4070,-1174,480,0,392521,249405,7179,0,-687,6164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48714,455963,0,0,0,1,360000,547272,43366,495000,0,...,1396,-421,0,0,2317500,529953,0,0,-203,15696
48715,455965,0,1,1,0,315000,900000,57519,900000,0,...,121,-619,36,0,3639113,452155,0,0,-409,18879
48716,456007,0,0,1,0,135000,318645,16398,216000,0,...,0,0,0,0,0,0,0,0,0,0
48717,456008,0,0,1,0,81000,180000,13455,180000,0,...,-967,-1558,0,0,178597,96868,0,0,-978,4488
48718,456009,0,0,1,0,225000,360000,19530,360000,0,...,1441,0,0,0,229500,0,229500,0,-34,22950
48719,456010,0,0,1,1,112500,690313,35374,549000,0,...,-363,-1436,4160,0,460238,448014,0,0,-1032,14429
48720,456011,0,1,1,1,171000,323460,23134,270000,0,...,-730,-915,18,0,204175,92597,0,0,-791,32125
48721,456013,0,0,1,1,130500,468333,37129,382500,0,...,180,-97,0,0,89961,0,0,0,-64,0
48722,456028,0,0,1,0,220500,166500,13284,166500,0,...,4445,-1568,0,0,226534,0,0,0,-865,2913
48723,456058,0,0,0,1,67500,315000,16213,315000,0,...,879,-316,0,0,108783,87729,0,0,-163,5400
48724,456111,0,0,1,1,112500,514710,17707,387000,0,...,-538,-623,6267,0,146567,76887,14094,0,-368,9964
48725,456114,0,0,0,0,45000,450000,24543,450000,0,...,-887,-1560,0,0,158989,64254,0,0,-900,6376
48726,456115,0,0,1,1,225000,1002339,37917,846000,0,...,-864,-1876,7798,0,442481,217072,0,0,-1105,9826
48727,456116,0,0,0,1,180000,149256,15291,135000,0,...,-1011,-759,0,0,52796,2560,0,0,-1023,5314
48728,456119,0,0,1,0,247500,685386,38398,585000,0,...,-477,-742,5305,0,187783,0,0,0,-34,6187
48729,456120,0,0,0,2,81000,135000,16020,135000,0,...,0,0,0,0,0,0,0,0,0,0
48730,456122,0,1,0,2,157500,445095,40824,405000,0,...,-227,-709,141,0,90634,47698,0,0,-362,6576
48731,456123,0,1,1,0,112500,450000,28890,450000,0,...,-1287,-1135,0,0,114363,0,0,0,-990,0
48732,456166,0,0,1,0,189000,479700,54382,450000,0,...,-959,-1445,6399,0,868320,0,0,0,-1308,66897
48733,456167,0,0,1,0,135000,1047771,37764,904500,0,...,-904,-904,0,0,202079,0,0,0,-982,0
48734,456168,0,0,1,0,135000,835686,46660,765000,0,...,-472,-611,0,0,981000,0,0,0,-586,0
48735,456169,0,0,0,0,85500,109008,7411,90000,0,...,0,0,0,0,0,0,0,0,0,0
48736,456170,0,1,1,0,157500,500490,48888,450000,0,...,-1155,-524,0,0,120460,0,0,0,-384,12189
48737,456189,0,0,1,0,270000,360000,28570,360000,0,...,-566,-2061,0,0,317551,204525,0,0,-726,9226
48738,456202,0,1,0,3,135000,252022,23112,217561,0,...,692,-420,0,0,76059,3064,0,0,-123,0
48739,456221,0,0,1,0,121500,412560,17473,270000,0,...,7,-457,11427,0,223759,111294,0,0,-282,5960
48740,456222,0,0,0,2,157500,622413,31909,495000,0,...,0,0,0,0,0,0,0,0,0,0
48741,456223,0,1,1,1,202500,315000,33205,315000,0,...,-382,-412,0,0,431261,4268,7300,0,-308,1263
48742,456224,0,0,0,0,225000,450000,25128,450000,0,...,-865,-1530,1492,0,226393,52511,0,0,-907,4608
48743,456250,0,1,0,0,135000,312768,24709,270000,0,...,1288,-760,0,0,1028819,744013,19422,0,-60,154567

In [7]:
test_enhanced_loan_history = pd.merge(test_non_na,installments, on='SK_ID_CURR', how='left')

In [8]:
test_enhanced_loan_history.to_csv('test_enhanced_loan_history.csv', index=False)